/* AUTO-GENERATED by scripts/generate-build-config.js — do not edit. */
window.__RENTBILL_SB_URL__ = 'https://kkixhxrniodyndgzkqgq.supabase.co';
window.__RENTBILL_SB_KEY__ = 'sb_publishable_zy5YRiETmug7i0qUII8pJQ_fVrF1th-';
