-- ============================================================================
-- RentBill Pro — Safe Database Upgrade Migration (Single-User Architecture)
-- Run this in Supabase SQL Editor to upgrade an existing database without losing data.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- 1. ENSURE NEW COLUMNS EXIST (IDEMPOTENT)
-- ============================================================================

-- Profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_disabled BOOLEAN NOT NULL DEFAULT FALSE;

-- Units (ensure both unit_name and unit_number exist and are kept in sync)
ALTER TABLE public.units ADD COLUMN IF NOT EXISTS unit_name TEXT;
ALTER TABLE public.units ADD COLUMN IF NOT EXISTS unit_number TEXT;
UPDATE public.units SET unit_name = unit_number WHERE unit_name IS NULL AND unit_number IS NOT NULL;
UPDATE public.units SET unit_number = unit_name WHERE unit_number IS NULL AND unit_name IS NOT NULL;

-- Renters
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS pending_arrears BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS maint_charge BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS eb_per_unit_price NUMERIC(10, 2) NOT NULL DEFAULT 8.00;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS initial_eb_reading BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS water_calc_mode TEXT NOT NULL DEFAULT 'FIXED';
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS water_fixed_charge BIGINT NOT NULL DEFAULT 150;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS water_per_unit_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS initial_water_reading BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS agreement_start_date DATE;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS agreement_expiry_date DATE;

-- Bills
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS period_start_date DATE;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS period_end_date DATE;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS bill_date DATE DEFAULT CURRENT_DATE;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS write_off_amount BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS write_off_reason TEXT;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS discount_amount BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS voided_at TIMESTAMPTZ;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS voided_by UUID;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS void_reason TEXT;

-- Payments
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMPTZ;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS reversed_by UUID;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS reversal_reason TEXT;

-- Create maintenance_tasks table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.maintenance_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    property_id BIGINT REFERENCES public.properties(id) ON DELETE SET NULL,
    unit_id BIGINT REFERENCES public.units(id) ON DELETE SET NULL,
    renter_id BIGINT REFERENCES public.renters(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT,
    priority TEXT NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'EMERGENCY')),
    status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    estimated_cost BIGINT DEFAULT 0,
    actual_cost BIGINT DEFAULT 0,
    reported_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    assigned_to TEXT,
    due_date DATE,
    completed_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- ============================================================================
-- 2. SAFE FOREIGN KEY CONSTRAINT UPGRADE (ON DELETE SET NULL)
-- ============================================================================

DO $$
BEGIN
  ALTER TABLE public.renters DROP CONSTRAINT IF EXISTS renters_user_id_fkey;
  ALTER TABLE public.renters ADD CONSTRAINT renters_user_id_fkey 
    FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.bills DROP CONSTRAINT IF EXISTS bills_voided_by_fkey;
  ALTER TABLE public.bills ADD CONSTRAINT bills_voided_by_fkey 
    FOREIGN KEY (voided_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_verified_by_fkey;
  ALTER TABLE public.payments ADD CONSTRAINT payments_verified_by_fkey 
    FOREIGN KEY (verified_by) REFERENCES public.profiles(id) ON DELETE SET NULL;
  
  ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_reversed_by_fkey;
  ALTER TABLE public.payments ADD CONSTRAINT payments_reversed_by_fkey 
    FOREIGN KEY (reversed_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.expenses DROP CONSTRAINT IF EXISTS expenses_created_by_fkey;
  ALTER TABLE public.expenses ADD CONSTRAINT expenses_created_by_fkey 
    FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.owner_withdrawals DROP CONSTRAINT IF EXISTS owner_withdrawals_created_by_fkey;
  ALTER TABLE public.owner_withdrawals ADD CONSTRAINT owner_withdrawals_created_by_fkey 
    FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.documents DROP CONSTRAINT IF EXISTS documents_created_by_fkey;
  ALTER TABLE public.documents ADD CONSTRAINT documents_created_by_fkey 
    FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.documents DROP CONSTRAINT IF EXISTS documents_entity_type_check;
  ALTER TABLE public.documents ADD CONSTRAINT documents_entity_type_check 
    CHECK (entity_type IN ('PROPERTY', 'UNIT', 'RENTER', 'OWNER', 'GENERAL'));

  ALTER TABLE public.maintenance_tasks DROP CONSTRAINT IF EXISTS maintenance_tasks_reported_by_fkey;
  ALTER TABLE public.maintenance_tasks ADD CONSTRAINT maintenance_tasks_reported_by_fkey 
    FOREIGN KEY (reported_by) REFERENCES public.profiles(id) ON DELETE SET NULL;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- ============================================================================
-- 3. SAFE DASHBOARD USER DELETION TRIGGERS
-- ============================================================================

CREATE OR REPLACE FUNCTION public.handle_profile_before_delete()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.renters SET user_id = NULL WHERE user_id = OLD.id;
  UPDATE public.bills SET voided_by = NULL WHERE voided_by = OLD.id;
  UPDATE public.payments SET verified_by = NULL WHERE verified_by = OLD.id;
  UPDATE public.payments SET reversed_by = NULL WHERE reversed_by = OLD.id;
  UPDATE public.expenses SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.owner_withdrawals SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.documents SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.maintenance_tasks SET reported_by = NULL WHERE reported_by = OLD.id;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_handle_profile_before_delete ON public.profiles;
CREATE TRIGGER trg_handle_profile_before_delete
  BEFORE DELETE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_profile_before_delete();

CREATE OR REPLACE FUNCTION public.handle_auth_user_before_delete()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.renters SET user_id = NULL WHERE user_id = OLD.id;
  UPDATE public.bills SET voided_by = NULL WHERE voided_by = OLD.id;
  UPDATE public.payments SET verified_by = NULL WHERE verified_by = OLD.id;
  UPDATE public.payments SET reversed_by = NULL WHERE reversed_by = OLD.id;
  UPDATE public.expenses SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.owner_withdrawals SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.documents SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.maintenance_tasks SET reported_by = NULL WHERE reported_by = OLD.id;

  BEGIN
    UPDATE storage.objects SET owner = NULL WHERE owner = OLD.id;
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  DELETE FROM public.profiles WHERE id = OLD.id;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_deleted ON auth.users;
CREATE TRIGGER on_auth_user_deleted
  BEFORE DELETE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_auth_user_before_delete();

-- ============================================================================
-- 4. FINANCIAL TRIGGERS (CALCULATIONS & RECONCILIATION)
-- ============================================================================

CREATE OR REPLACE FUNCTION public.calculate_bill_amounts()
RETURNS TRIGGER AS $$
BEGIN
  NEW.gross_amount := COALESCE(NEW.rent_amount, 0) + 
                      COALESCE(NEW.maint_amount, 0) + 
                      COALESCE(NEW.eb_amount, 0) + 
                      COALESCE(NEW.water_amount, 0) + 
                      COALESCE(NEW.arrears_included, 0) + 
                      COALESCE(NEW.late_fee, 0) + 
                      COALESCE(NEW.others, 0);

  NEW.net_amount := GREATEST(0, NEW.gross_amount - COALESCE(NEW.discount_amount, 0));

  IF NEW.status != 'VOID' THEN
    IF NEW.paid_amount >= NEW.net_amount AND NEW.net_amount > 0 THEN
      NEW.status := 'PAID';
    ELSIF NEW.paid_amount > 0 THEN
      NEW.status := 'PARTIAL';
    ELSE
      NEW.status := 'UNPAID';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_calculate_bill_amounts ON public.bills;
CREATE TRIGGER trg_calculate_bill_amounts
  BEFORE INSERT OR UPDATE ON public.bills
  FOR EACH ROW EXECUTE FUNCTION public.calculate_bill_amounts();

CREATE OR REPLACE FUNCTION public.sync_bill_paid_amount()
RETURNS TRIGGER AS $$
DECLARE
  v_bill_id BIGINT;
  v_total_paid BIGINT;
  v_net_amount BIGINT;
  v_bill_status TEXT;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_bill_id := OLD.bill_id;
  ELSE
    v_bill_id := NEW.bill_id;
  END IF;

  SELECT COALESCE(SUM(amount), 0) INTO v_total_paid
  FROM public.payments
  WHERE bill_id = v_bill_id
    AND deleted_at IS NULL
    AND reversed_at IS NULL
    AND (proof_status IS NULL OR proof_status IN ('NONE', 'VERIFIED'));

  SELECT net_amount, status INTO v_net_amount, v_bill_status
  FROM public.bills
  WHERE id = v_bill_id;

  IF v_bill_status != 'VOID' THEN
    IF v_total_paid >= v_net_amount AND v_net_amount > 0 THEN
      v_bill_status := 'PAID';
    ELSIF v_total_paid > 0 THEN
      v_bill_status := 'PARTIAL';
    ELSE
      v_bill_status := 'UNPAID';
    END IF;

    UPDATE public.bills
    SET paid_amount = v_total_paid,
        status = v_bill_status,
        updated_at = NOW()
    WHERE id = v_bill_id;
  ELSE
    UPDATE public.bills
    SET paid_amount = v_total_paid,
        updated_at = NOW()
    WHERE id = v_bill_id;
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_sync_bill_paid_amount ON public.payments;
CREATE TRIGGER trg_sync_bill_paid_amount
  AFTER INSERT OR UPDATE OR DELETE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.sync_bill_paid_amount();

-- ============================================================================
-- 5. SECURITY RPC FUNCTIONS & CLEANUP OF OBSOLETE FUNCTIONS
-- ============================================================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN FALSE; END IF;
  RETURN COALESCE((SELECT role = 'ADMIN' FROM public.profiles WHERE id = auth.uid()), FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Clean up obsolete ledger views and reconciliation function
DROP VIEW IF EXISTS public.v_ledger_accounts CASCADE;
DROP VIEW IF EXISTS public.v_ledger_entries CASCADE;
DROP FUNCTION IF EXISTS public.fn_reconcile_ledger() CASCADE;

-- Clean up obsolete multi-user, staff, auditor, and tenant RPC functions
DROP FUNCTION IF EXISTS public.is_staff() CASCADE;
DROP FUNCTION IF EXISTS public.is_auditor() CASCADE;
DROP FUNCTION IF EXISTS public.admin_list_all_users() CASCADE;
DROP FUNCTION IF EXISTS public.admin_create_user(TEXT, TEXT, TEXT, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.admin_update_user_password(UUID, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.admin_change_user_role(UUID, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.admin_toggle_user_status(UUID, BOOLEAN) CASCADE;
DROP FUNCTION IF EXISTS public.admin_delete_user(UUID) CASCADE;
DROP FUNCTION IF EXISTS public.admin_list_tenants_with_auth() CASCADE;
DROP FUNCTION IF EXISTS public.admin_create_tenant_user(TEXT, TEXT, TEXT, BIGINT) CASCADE;
DROP FUNCTION IF EXISTS public.admin_reset_tenant_password(UUID, TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.admin_delete_tenant_login(BIGINT, UUID) CASCADE;
DROP FUNCTION IF EXISTS public.admin_toggle_tenant_login_status(BIGINT, UUID, BOOLEAN) CASCADE;
DROP FUNCTION IF EXISTS public.get_login_email_for_identifier(TEXT) CASCADE;
DROP FUNCTION IF EXISTS public.tenant_link_own_lease() CASCADE;

CREATE OR REPLACE FUNCTION public.resolve_login_email(p_identifier TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_clean TEXT := TRIM(COALESCE(p_identifier, ''));
  v_email TEXT;
BEGIN
  IF v_clean = '' THEN
    RETURN NULL;
  END IF;

  -- 1. If identifier is already an email, return as-is
  IF v_clean LIKE '%@%' THEN
    RETURN LOWER(v_clean);
  END IF;

  -- 2. Lookup by username in public.profiles (case-insensitive)
  SELECT email INTO v_email
  FROM public.profiles
  WHERE LOWER(username) = LOWER(v_clean)
  LIMIT 1;

  IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN
    RETURN LOWER(v_email);
  END IF;

  -- 3. Lookup in auth.users by raw_user_meta_data->>'username'
  SELECT email INTO v_email
  FROM auth.users
  WHERE LOWER(COALESCE(raw_user_meta_data->>'username', '')) = LOWER(v_clean)
  LIMIT 1;

  IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN
    RETURN LOWER(v_email);
  END IF;

  -- 4. Fallback lookup by renter name
  SELECT email INTO v_email
  FROM public.renters
  WHERE LOWER(name) = LOWER(v_clean)
    AND deleted_at IS NULL
  ORDER BY is_active DESC
  LIMIT 1;

  RETURN LOWER(v_email);
END;
$$;

-- ============================================================================
-- 6. PERMISSIONS & GRANTS
-- ============================================================================

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_login_email(TEXT) TO authenticated, anon;

-- ============================================================================
-- 7. ROW LEVEL SECURITY REFRESH
-- ============================================================================

DO $$
BEGIN
  -- Safe RLS enable
  ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.owners ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.renters ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.owner_withdrawals ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.maintenance_tasks ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

  -- Drop public anonymous access policies (ensure 100% login required)
  DROP POLICY IF EXISTS "Anon read public bills" ON public.bills;
  DROP POLICY IF EXISTS "Anon read public payments" ON public.payments;
  DROP POLICY IF EXISTS "Anon read public renters" ON public.renters;
  DROP POLICY IF EXISTS "Anon read public units" ON public.units;
  DROP POLICY IF EXISTS "Anon read public properties" ON public.properties;
  DROP POLICY IF EXISTS "Anon read public owners" ON public.owners;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;
