-- ============================================================================
-- RentBill Pro — Safe Database Upgrade Migration (Single-User Architecture)
-- Run this in Supabase SQL Editor to upgrade an existing database without losing data.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- 1. ENSURE NEW COLUMNS EXIST (IDEMPOTENT)
-- ============================================================================

-- Profiles
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS is_disabled BOOLEAN NOT NULL DEFAULT FALSE;

-- Renters
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS pending_arrears BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS maint_charge BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS eb_per_unit_price NUMERIC(10, 2) NOT NULL DEFAULT 8.00;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS initial_eb_reading BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS water_calc_mode TEXT NOT NULL DEFAULT 'FIXED';
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS water_fixed_charge BIGINT NOT NULL DEFAULT 150;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS water_per_unit_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS initial_water_reading BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS agreement_start_date DATE;
ALTER TABLE public.renters ADD COLUMN IF NOT EXISTS agreement_expiry_date DATE;

-- Bills
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS period_start_date DATE;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS period_end_date DATE;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS bill_date DATE DEFAULT CURRENT_DATE;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS due_date DATE;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS write_off_amount BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS write_off_reason TEXT;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS discount_amount BIGINT NOT NULL DEFAULT 0;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS voided_at TIMESTAMPTZ;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS voided_by UUID;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS void_reason TEXT;

-- Payments
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS reversed_at TIMESTAMPTZ;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS reversed_by UUID;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS reversal_reason TEXT;

-- Create maintenance_tasks table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.maintenance_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    property_id BIGINT REFERENCES public.properties(id) ON DELETE SET NULL,
    unit_id BIGINT REFERENCES public.units(id) ON DELETE SET NULL,
    renter_id BIGINT REFERENCES public.renters(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT,
    priority TEXT NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'EMERGENCY')),
    status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    estimated_cost BIGINT DEFAULT 0,
    actual_cost BIGINT DEFAULT 0,
    reported_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    assigned_to TEXT,
    due_date DATE,
    completed_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- ============================================================================
-- 2. SAFE FOREIGN KEY CONSTRAINT UPGRADE (ON DELETE SET NULL)
-- ============================================================================

DO $$
BEGIN
  ALTER TABLE public.renters DROP CONSTRAINT IF EXISTS renters_user_id_fkey;
  ALTER TABLE public.renters ADD CONSTRAINT renters_user_id_fkey 
    FOREIGN KEY (user_id) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.bills DROP CONSTRAINT IF EXISTS bills_voided_by_fkey;
  ALTER TABLE public.bills ADD CONSTRAINT bills_voided_by_fkey 
    FOREIGN KEY (voided_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_verified_by_fkey;
  ALTER TABLE public.payments ADD CONSTRAINT payments_verified_by_fkey 
    FOREIGN KEY (verified_by) REFERENCES public.profiles(id) ON DELETE SET NULL;
  
  ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_reversed_by_fkey;
  ALTER TABLE public.payments ADD CONSTRAINT payments_reversed_by_fkey 
    FOREIGN KEY (reversed_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.expenses DROP CONSTRAINT IF EXISTS expenses_created_by_fkey;
  ALTER TABLE public.expenses ADD CONSTRAINT expenses_created_by_fkey 
    FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.owner_withdrawals DROP CONSTRAINT IF EXISTS owner_withdrawals_created_by_fkey;
  ALTER TABLE public.owner_withdrawals ADD CONSTRAINT owner_withdrawals_created_by_fkey 
    FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.documents DROP CONSTRAINT IF EXISTS documents_created_by_fkey;
  ALTER TABLE public.documents ADD CONSTRAINT documents_created_by_fkey 
    FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.maintenance_tasks DROP CONSTRAINT IF EXISTS maintenance_tasks_reported_by_fkey;
  ALTER TABLE public.maintenance_tasks ADD CONSTRAINT maintenance_tasks_reported_by_fkey 
    FOREIGN KEY (reported_by) REFERENCES public.profiles(id) ON DELETE SET NULL;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- ============================================================================
-- 3. SAFE DASHBOARD USER DELETION TRIGGERS
-- ============================================================================

CREATE OR REPLACE FUNCTION public.handle_profile_before_delete()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.renters SET user_id = NULL WHERE user_id = OLD.id;
  UPDATE public.bills SET voided_by = NULL WHERE voided_by = OLD.id;
  UPDATE public.payments SET verified_by = NULL WHERE verified_by = OLD.id;
  UPDATE public.payments SET reversed_by = NULL WHERE reversed_by = OLD.id;
  UPDATE public.expenses SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.owner_withdrawals SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.documents SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.maintenance_tasks SET reported_by = NULL WHERE reported_by = OLD.id;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_handle_profile_before_delete ON public.profiles;
CREATE TRIGGER trg_handle_profile_before_delete
  BEFORE DELETE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_profile_before_delete();

CREATE OR REPLACE FUNCTION public.handle_auth_user_before_delete()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.renters SET user_id = NULL WHERE user_id = OLD.id;
  UPDATE public.bills SET voided_by = NULL WHERE voided_by = OLD.id;
  UPDATE public.payments SET verified_by = NULL WHERE verified_by = OLD.id;
  UPDATE public.payments SET reversed_by = NULL WHERE reversed_by = OLD.id;
  UPDATE public.expenses SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.owner_withdrawals SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.documents SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.maintenance_tasks SET reported_by = NULL WHERE reported_by = OLD.id;

  BEGIN
    UPDATE storage.objects SET owner = NULL WHERE owner = OLD.id;
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  DELETE FROM public.profiles WHERE id = OLD.id;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_deleted ON auth.users;
CREATE TRIGGER on_auth_user_deleted
  BEFORE DELETE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_auth_user_before_delete();

-- ============================================================================
-- 4. FINANCIAL TRIGGERS (CALCULATIONS & RECONCILIATION)
-- ============================================================================

CREATE OR REPLACE FUNCTION public.calculate_bill_amounts()
RETURNS TRIGGER AS $$
BEGIN
  NEW.gross_amount := COALESCE(NEW.rent_amount, 0) + 
                      COALESCE(NEW.maint_amount, 0) + 
                      COALESCE(NEW.eb_amount, 0) + 
                      COALESCE(NEW.water_amount, 0) + 
                      COALESCE(NEW.arrears_included, 0) + 
                      COALESCE(NEW.late_fee, 0) + 
                      COALESCE(NEW.others, 0);

  NEW.net_amount := GREATEST(0, NEW.gross_amount - COALESCE(NEW.discount_amount, 0));

  IF NEW.status != 'VOID' THEN
    IF NEW.paid_amount >= NEW.net_amount AND NEW.net_amount > 0 THEN
      NEW.status := 'PAID';
    ELSIF NEW.paid_amount > 0 THEN
      NEW.status := 'PARTIAL';
    ELSE
      NEW.status := 'UNPAID';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_calculate_bill_amounts ON public.bills;
CREATE TRIGGER trg_calculate_bill_amounts
  BEFORE INSERT OR UPDATE ON public.bills
  FOR EACH ROW EXECUTE FUNCTION public.calculate_bill_amounts();

CREATE OR REPLACE FUNCTION public.sync_bill_paid_amount()
RETURNS TRIGGER AS $$
DECLARE
  v_bill_id BIGINT;
  v_total_paid BIGINT;
  v_net_amount BIGINT;
  v_bill_status TEXT;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_bill_id := OLD.bill_id;
  ELSE
    v_bill_id := NEW.bill_id;
  END IF;

  SELECT COALESCE(SUM(amount), 0) INTO v_total_paid
  FROM public.payments
  WHERE bill_id = v_bill_id
    AND deleted_at IS NULL
    AND reversed_at IS NULL
    AND (proof_status IS NULL OR proof_status IN ('NONE', 'VERIFIED'));

  SELECT net_amount, status INTO v_net_amount, v_bill_status
  FROM public.bills
  WHERE id = v_bill_id;

  IF v_bill_status != 'VOID' THEN
    IF v_total_paid >= v_net_amount AND v_net_amount > 0 THEN
      v_bill_status := 'PAID';
    ELSIF v_total_paid > 0 THEN
      v_bill_status := 'PARTIAL';
    ELSE
      v_bill_status := 'UNPAID';
    END IF;

    UPDATE public.bills
    SET paid_amount = v_total_paid,
        status = v_bill_status,
        updated_at = NOW()
    WHERE id = v_bill_id;
  ELSE
    UPDATE public.bills
    SET paid_amount = v_total_paid,
        updated_at = NOW()
    WHERE id = v_bill_id;
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_sync_bill_paid_amount ON public.payments;
CREATE TRIGGER trg_sync_bill_paid_amount
  AFTER INSERT OR UPDATE OR DELETE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.sync_bill_paid_amount();

-- ============================================================================
-- 5. FINANCIAL JOURNAL & LEDGER VIEWS
-- ============================================================================

CREATE OR REPLACE VIEW public.v_ledger_entries
WITH (security_invoker = true) AS
  SELECT
    'BILL'::text                                                                 AS source_type,
    b.id                                                                         AS source_id,
    b.uuid                                                                       AS source_uuid,
    COALESCE(b.bill_date, b.created_at::date)                                   AS entry_date,
    b.renter_id                                                                  AS renter_id,
    r.name                                                                       AS renter_name,
    r.unit_id                                                                    AS unit_id,
    'RECEIVABLE_INVOICED'::text                                                  AS account,
    b.net_amount                                                                 AS amount,
    'INV ' || b.billing_period || ' net payable'                                 AS description,
    b.created_at                                                                 AS created_at
  FROM public.bills b
  JOIN public.renters r ON r.id = b.renter_id
  WHERE b.deleted_at IS NULL
    AND b.status != 'VOID'
    AND b.voided_at IS NULL

  UNION ALL

  SELECT
    'BILL'::text                                                                 AS source_type,
    b.id                                                                         AS source_id,
    b.uuid                                                                       AS source_uuid,
    COALESCE(b.bill_date, b.created_at::date)                                   AS entry_date,
    b.renter_id                                                                  AS renter_id,
    r.name                                                                       AS renter_name,
    r.unit_id                                                                    AS unit_id,
    'RECEIVABLE_WRITTEN_OFF'::text                                               AS account,
    b.write_off_amount                                                           AS amount,
    COALESCE('Write-off: ' || b.write_off_reason, 'Invoice balance written off') AS description,
    b.created_at                                                                 AS created_at
  FROM public.bills b
  JOIN public.renters r ON r.id = b.renter_id
  WHERE b.deleted_at IS NULL
    AND b.status != 'VOID'
    AND b.voided_at IS NULL
    AND COALESCE(b.write_off_amount, 0) > 0

  UNION ALL

  SELECT
    'PAYMENT'::text                                                              AS source_type,
    p.id                                                                         AS source_id,
    p.uuid                                                                       AS source_uuid,
    p.payment_date::date                                                         AS entry_date,
    p.renter_id                                                                  AS renter_id,
    r.name                                                                       AS renter_name,
    r.unit_id                                                                    AS unit_id,
    'CASH_IN'::text                                                              AS account,
    p.amount                                                                     AS amount,
    COALESCE(p.payment_method, 'Payment') || ' against bill #' || p.bill_id      AS description,
    p.created_at                                                                 AS created_at
  FROM public.payments p
  JOIN public.renters r ON r.id = p.renter_id
  WHERE p.deleted_at IS NULL
    AND p.reversed_at IS NULL
    AND (p.proof_status IS NULL OR p.proof_status IN ('NONE', 'VERIFIED'))

  UNION ALL

  SELECT
    'EXPENSE'::text                                                              AS source_type,
    e.id                                                                         AS source_id,
    e.uuid                                                                       AS source_uuid,
    e.expense_date                                                               AS entry_date,
    NULL::bigint                                                                 AS renter_id,
    NULL::text                                                                   AS renter_name,
    NULL::bigint                                                                 AS unit_id,
    'CASH_OUT_EXPENSES'::text                                                    AS account,
    e.amount                                                                     AS amount,
    '[' || e.category || '] ' || COALESCE(e.description, 'Expense')              AS description,
    e.created_at                                                                 AS created_at
  FROM public.expenses e
  WHERE e.deleted_at IS NULL

  UNION ALL

  SELECT
    'WITHDRAWAL'::text                                                           AS source_type,
    w.id                                                                         AS source_id,
    w.uuid                                                                       AS source_uuid,
    w.withdrawal_date                                                            AS entry_date,
    NULL::bigint                                                                 AS renter_id,
    o.name                                                                       AS renter_name,
    NULL::bigint                                                                 AS unit_id,
    'CASH_OUT_WITHDRAWALS'::text                                                 AS account,
    w.amount                                                                     AS amount,
    'Owner payout to ' || o.name || COALESCE(' (' || w.payment_method || ')', '') AS description,
    w.created_at                                                                 AS created_at
  FROM public.owner_withdrawals w
  JOIN public.owners o ON o.id = w.owner_id
  WHERE w.deleted_at IS NULL;

CREATE OR REPLACE VIEW public.v_ledger_accounts
WITH (security_invoker = true) AS
  SELECT
    account,
    COUNT(*)                AS entry_count,
    COALESCE(SUM(amount), 0) AS balance
  FROM public.v_ledger_entries
  GROUP BY account;

CREATE OR REPLACE FUNCTION public.fn_reconcile_ledger()
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  WITH totals AS (
    SELECT
      COALESCE(SUM(amount) FILTER (WHERE account = 'RECEIVABLE_INVOICED'), 0)     AS total_billed,
      COALESCE(SUM(amount) FILTER (WHERE account = 'RECEIVABLE_WRITTEN_OFF'), 0)  AS total_written_off,
      COALESCE(SUM(amount) FILTER (WHERE account = 'CASH_IN'), 0)                  AS total_collected,
      COALESCE(SUM(amount) FILTER (WHERE account = 'CASH_OUT_EXPENSES'), 0)        AS total_expenses,
      COALESCE(SUM(amount) FILTER (WHERE account = 'CASH_OUT_WITHDRAWALS'), 0)     AS total_withdrawn
    FROM public.v_ledger_entries
  ),
  per_bill AS (
    SELECT
      b.id,
      b.net_amount,
      COALESCE(b.write_off_amount, 0) AS written_off,
      COALESCE(SUM(p.amount), 0) AS collected
    FROM public.bills b
    LEFT JOIN public.payments p
      ON p.bill_id = b.id
      AND p.deleted_at IS NULL
      AND p.reversed_at IS NULL
      AND (p.proof_status IS NULL OR p.proof_status IN ('NONE', 'VERIFIED'))
    WHERE b.deleted_at IS NULL
      AND b.status != 'VOID'
      AND b.voided_at IS NULL
    GROUP BY b.id, b.net_amount, b.write_off_amount
  ),
  bill_snapshot AS (
    SELECT
      SUM(net_amount) AS billed,
      SUM(written_off) AS written_off,
      SUM(collected) AS collected,
      SUM(net_amount) - SUM(written_off) - SUM(collected) AS outstanding
    FROM per_bill
  ),
  calcs AS (
    SELECT
      t.total_billed,
      t.total_written_off,
      t.total_collected,
      t.total_expenses,
      t.total_withdrawn,
      bs.billed AS per_bill_billed,
      bs.written_off AS per_bill_written_off,
      bs.collected AS per_bill_collected,
      bs.outstanding AS outstanding,
      (t.total_billed + t.total_written_off) - t.total_collected AS net_receivable,
      t.total_collected - (t.total_expenses + t.total_withdrawn) AS net_cash_flow
    FROM totals t, bill_snapshot bs
  )
  SELECT jsonb_build_object(
    'total_billed',            calcs.total_billed,
    'total_written_off',       calcs.total_written_off,
    'total_collected',         calcs.total_collected,
    'total_expenses',          calcs.total_expenses,
    'total_withdrawn',         calcs.total_withdrawn,
    'outstanding',             calcs.outstanding,
    'net_receivable',          calcs.net_receivable,
    'net_cash_flow',           calcs.net_cash_flow,
    'accounts', (
      SELECT jsonb_object_agg(account, balance) FROM public.v_ledger_accounts
    ),
    'integrity'::text, jsonb_build_object(
      'billed_matches',        calcs.total_billed = calcs.per_bill_billed,
      'collected_matches',     calcs.total_collected = calcs.per_bill_collected,
      'written_off_matches',   calcs.total_written_off = calcs.per_bill_written_off,
      'outstanding_non_negative', calcs.outstanding >= 0
    )
  )
  FROM calcs;
$$;

-- ============================================================================
-- 6. SECURITY & COMPATIBILITY RPC FUNCTIONS
-- ============================================================================

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN FALSE; END IF;
  RETURN COALESCE((SELECT role = 'ADMIN' FROM public.profiles WHERE id = auth.uid()), FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS BOOLEAN AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN FALSE; END IF;
  RETURN COALESCE((SELECT role IN ('ADMIN', 'STAFF') FROM public.profiles WHERE id = auth.uid()), FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION public.is_auditor()
RETURNS BOOLEAN AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN FALSE; END IF;
  RETURN COALESCE((SELECT role IN ('ADMIN', 'AUDITOR') FROM public.profiles WHERE id = auth.uid()), FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION public.admin_list_all_users()
RETURNS TABLE (
  user_id UUID,
  username TEXT,
  email TEXT,
  role TEXT,
  is_disabled BOOLEAN,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  last_sign_in_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    p.id AS user_id,
    p.username,
    p.email,
    p.role,
    p.is_disabled,
    p.created_at,
    p.updated_at,
    au.last_sign_in_at
  FROM public.profiles p
  LEFT JOIN auth.users au ON au.id = p.id
  ORDER BY p.role, p.username;
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_create_user(
  p_email TEXT,
  p_password TEXT,
  p_role TEXT DEFAULT 'ADMIN',
  p_username TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_user_id UUID;
  v_encrypted_pw TEXT;
BEGIN
  v_user_id := gen_random_uuid();
  v_encrypted_pw := crypt(p_password, gen_salt('bf'));

  INSERT INTO auth.users (
    id, instance_id, email, encrypted_password, email_confirmed_at,
    raw_app_meta_data, raw_user_meta_data, created_at, updated_at, role, aud
  ) VALUES (
    v_user_id, '00000000-0000-0000-0000-000000000000', LOWER(TRIM(p_email)), v_encrypted_pw, NOW(),
    jsonb_build_object('provider', 'email', 'providers', jsonb_build_array('email')),
    jsonb_build_object('username', COALESCE(p_username, SPLIT_PART(p_email, '@', 1)), 'role', p_role),
    NOW(), NOW(), 'authenticated', 'authenticated'
  );

  INSERT INTO public.profiles (id, username, email, role)
  VALUES (v_user_id, COALESCE(p_username, SPLIT_PART(p_email, '@', 1)), LOWER(TRIM(p_email)), p_role)
  ON CONFLICT (id) DO UPDATE SET role = EXCLUDED.role;

  RETURN jsonb_build_object('success', true, 'user_id', v_user_id);
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_update_user_password(
  p_user_id UUID,
  p_new_password TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  UPDATE auth.users
  SET encrypted_password = crypt(p_new_password, gen_salt('bf')),
      updated_at = NOW()
  WHERE id = p_user_id;

  RETURN jsonb_build_object('success', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_change_user_role(
  p_user_id UUID,
  p_new_role TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.profiles
  SET role = p_new_role, updated_at = NOW()
  WHERE id = p_user_id;

  RETURN jsonb_build_object('success', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_toggle_user_status(
  p_user_id UUID,
  p_disabled BOOLEAN
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.profiles
  SET is_disabled = p_disabled, updated_at = NOW()
  WHERE id = p_user_id;

  RETURN jsonb_build_object('success', true);
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_delete_user(
  p_user_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  UPDATE public.renters SET user_id = NULL WHERE user_id = p_user_id;
  UPDATE public.bills SET voided_by = NULL WHERE voided_by = p_user_id;
  UPDATE public.payments SET verified_by = NULL WHERE verified_by = p_user_id;
  UPDATE public.payments SET reversed_by = NULL WHERE reversed_by = p_user_id;
  UPDATE public.expenses SET created_by = NULL WHERE created_by = p_user_id;
  UPDATE public.owner_withdrawals SET created_by = NULL WHERE created_by = p_user_id;
  UPDATE public.documents SET created_by = NULL WHERE created_by = p_user_id;
  UPDATE public.maintenance_tasks SET reported_by = NULL WHERE reported_by = p_user_id;

  DELETE FROM public.profiles WHERE id = p_user_id;
  DELETE FROM auth.users WHERE id = p_user_id;

  RETURN jsonb_build_object('success', true, 'deleted_user_id', p_user_id);
END;
$$;

-- ============================================================================
-- 7. PERMISSIONS & GRANTS
-- ============================================================================

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.is_auditor() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.is_staff() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.fn_reconcile_ledger() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_all_users() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_user(TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_user_password(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_change_user_role(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_toggle_user_status(UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_user(UUID) TO authenticated;

GRANT SELECT ON public.v_ledger_entries TO authenticated;
GRANT SELECT ON public.v_ledger_accounts TO authenticated;

-- ============================================================================
-- 8. ROW LEVEL SECURITY REFRESH
-- ============================================================================

DO $$
BEGIN
  -- Safe RLS enable
  ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.owners ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.renters ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.owner_withdrawals ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.maintenance_tasks ENABLE ROW LEVEL SECURITY;
  ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;
