-- ============================================================================
-- 🏢 RENTBILL PRO — ROBUST PRODUCTION DATABASE UPDATE & MIGRATION (100% AUDITED)
-- Safe to run on ANY existing or new Supabase PostgreSQL instance.
-- Preserves all existing properties, units, tenants, invoices, and payments.
-- ============================================================================

-- 1. Ensure required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1.1 Profiles Table & Auth Signup Trigger (idempotent — ensures existence)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT UNIQUE NOT NULL,
    email TEXT,
    role TEXT NOT NULL DEFAULT 'TENANT' CHECK (role IN ('ADMIN', 'TENANT', 'STAFF', 'AUDITOR')),
    is_disabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  BEGIN
    INSERT INTO public.profiles (id, username, email, role)
    VALUES (
      NEW.id,
      COALESCE(NEW.raw_user_meta_data->>'username', SPLIT_PART(NEW.email, '@', 1)),
      NEW.email,
      COALESCE(NEW.raw_user_meta_data->>'role', 'TENANT')
    )
    ON CONFLICT (id) DO UPDATE
      SET email = EXCLUDED.email,
          updated_at = NOW();
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  BEGIN
    UPDATE public.renters
    SET user_id = NEW.id,
        updated_at = NOW()
    WHERE (LOWER(email) = LOWER(NEW.email) OR user_id = NEW.id)
      AND deleted_at IS NULL;
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 2. Maintenance Tasks & Repair Work Orders Table
CREATE TABLE IF NOT EXISTS public.maintenance_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL DEFAULT 'PLUMBING' CHECK (category IN ('PLUMBING', 'ELECTRICAL', 'APPLIANCE', 'CLEANING', 'PAINTING', 'CARPENTRY', 'GENERAL', 'OTHER')),
    priority TEXT NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    property_id BIGINT REFERENCES public.properties(id) ON DELETE SET NULL,
    unit_id BIGINT REFERENCES public.units(id) ON DELETE SET NULL,
    renter_id BIGINT REFERENCES public.renters(id) ON DELETE SET NULL,
    reported_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    assigned_to TEXT,
    estimated_cost BIGINT DEFAULT 0,
    actual_cost BIGINT DEFAULT 0,
    scheduled_date DATE,
    completed_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_maint_property ON public.maintenance_tasks(property_id);
CREATE INDEX IF NOT EXISTS idx_maint_unit ON public.maintenance_tasks(unit_id);
CREATE INDEX IF NOT EXISTS idx_maint_renter ON public.maintenance_tasks(renter_id);
CREATE INDEX IF NOT EXISTS idx_maint_status ON public.maintenance_tasks(status);

-- 3. Dynamic Foreign Key Constraint Upgrade (Fix User Deletion Constraint Errors)
DO $$
BEGIN
  ALTER TABLE public.bills DROP CONSTRAINT IF EXISTS bills_voided_by_fkey;
  ALTER TABLE public.bills ADD CONSTRAINT bills_voided_by_fkey FOREIGN KEY (voided_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_verified_by_fkey;
  ALTER TABLE public.payments ADD CONSTRAINT payments_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id) ON DELETE SET NULL;
  
  ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_reversed_by_fkey;
  ALTER TABLE public.payments ADD CONSTRAINT payments_reversed_by_fkey FOREIGN KEY (reversed_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.expenses DROP CONSTRAINT IF EXISTS expenses_created_by_fkey;
  ALTER TABLE public.expenses ADD CONSTRAINT expenses_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.owner_withdrawals DROP CONSTRAINT IF EXISTS owner_withdrawals_created_by_fkey;
  ALTER TABLE public.owner_withdrawals ADD CONSTRAINT owner_withdrawals_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.documents DROP CONSTRAINT IF EXISTS documents_created_by_fkey;
  ALTER TABLE public.documents ADD CONSTRAINT documents_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- 4. Pure Admin Security Guard Function
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
DECLARE
  v_role TEXT;
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN FALSE;
  END IF;
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  RETURN COALESCE(v_role = 'ADMIN', FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 4.1 Staff & Auditor Role Helper Functions (needed for STAFF/AUDITOR RLS)
CREATE OR REPLACE FUNCTION public.is_auditor()
RETURNS BOOLEAN AS $$
DECLARE
  v_role TEXT;
BEGIN
  IF auth.uid() IS NULL THEN RETURN FALSE; END IF;
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  RETURN COALESCE(v_role = 'AUDITOR', FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE OR REPLACE FUNCTION public.is_staff()
RETURNS BOOLEAN AS $$
DECLARE
  v_role TEXT;
BEGIN
  IF auth.uid() IS NULL THEN RETURN FALSE; END IF;
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  RETURN COALESCE(v_role = 'STAFF', FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 5. Updated Row Level Security (RLS) Policies
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owner_withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_tasks ENABLE ROW LEVEL SECURITY;

-- Tenants View Own Lease
DROP POLICY IF EXISTS "Tenants view own lease" ON public.renters;
CREATE POLICY "Tenants view own lease" ON public.renters FOR SELECT TO authenticated USING (
  (
    user_id = auth.uid() 
    OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
    OR (
      LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
      AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
    )
  )
  AND deleted_at IS NULL
);

-- Tenants View Own Bills
DROP POLICY IF EXISTS "Tenants view own bills" ON public.bills;
CREATE POLICY "Tenants view own bills" ON public.bills FOR SELECT TO authenticated USING (
  renter_id IN (
    SELECT id FROM public.renters 
    WHERE (
      user_id = auth.uid() 
      OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
      OR (
        LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
        AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
      )
    )
    AND deleted_at IS NULL
  )
  AND deleted_at IS NULL
);

-- Tenants View Own Payments
DROP POLICY IF EXISTS "Tenants view own payments" ON public.payments;
CREATE POLICY "Tenants view own payments" ON public.payments FOR SELECT TO authenticated USING (
  renter_id IN (
    SELECT id FROM public.renters 
    WHERE (
      user_id = auth.uid() 
      OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
      OR (
        LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
        AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
      )
    )
    AND deleted_at IS NULL
  )
  AND deleted_at IS NULL
);

-- Maintenance Tasks Policies
DROP POLICY IF EXISTS "Admins full access to maintenance_tasks" ON public.maintenance_tasks;
CREATE POLICY "Admins full access to maintenance_tasks" ON public.maintenance_tasks FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Tenants view own maintenance_tasks" ON public.maintenance_tasks;
CREATE POLICY "Tenants view own maintenance_tasks" ON public.maintenance_tasks FOR SELECT TO authenticated USING (
  (
    reported_by = auth.uid()
    OR renter_id IN (
      SELECT id FROM public.renters 
      WHERE (
        user_id = auth.uid() 
        OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
        OR (
          LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
          AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
        )
      )
      AND deleted_at IS NULL
    )
  )
  AND deleted_at IS NULL
);

DROP POLICY IF EXISTS "Tenants submit maintenance_tasks" ON public.maintenance_tasks;
CREATE POLICY "Tenants submit maintenance_tasks" ON public.maintenance_tasks FOR INSERT TO authenticated WITH CHECK (
  reported_by = auth.uid() OR
  renter_id IN (
    SELECT id FROM public.renters 
    WHERE (
      user_id = auth.uid() 
      OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
      OR (
        LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
        AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
      )
    )
    AND deleted_at IS NULL
  )
);

-- Tenants View Assigned Owner (Landlord contact/UPI)
DROP POLICY IF EXISTS "Tenants view assigned owner" ON public.owners;
CREATE POLICY "Tenants view assigned owner" ON public.owners FOR SELECT TO authenticated USING (
  id IN (
    SELECT owner_id FROM public.renters
    WHERE (user_id = auth.uid() OR (email IS NOT NULL AND LOWER(email) = LOWER(auth.email())))
      AND deleted_at IS NULL
  )
);

-- Tenants View Their Property
DROP POLICY IF EXISTS "Tenants view property" ON public.properties;
CREATE POLICY "Tenants view property" ON public.properties FOR SELECT TO authenticated USING (
  id IN (
    SELECT u.property_id FROM public.units u
    JOIN public.renters r ON r.unit_id = u.id
    WHERE (r.user_id = auth.uid() OR (r.email IS NOT NULL AND LOWER(r.email) = LOWER(auth.email())))
      AND r.deleted_at IS NULL
  )
);

-- Tenants View Their Assigned Unit
DROP POLICY IF EXISTS "Tenants view assigned unit" ON public.units;
CREATE POLICY "Tenants view assigned unit" ON public.units FOR SELECT TO authenticated USING (
  id IN (
    SELECT unit_id FROM public.renters
    WHERE (user_id = auth.uid() OR (email IS NOT NULL AND LOWER(email) = LOWER(auth.email())))
      AND deleted_at IS NULL
  )
);

-- 6. Authentication RPC Functions (Universal Login & Tenant Management)

-- Resolve Login Email (Universal login wrapper)
DROP FUNCTION IF EXISTS public.get_login_email_for_identifier(TEXT);
DROP FUNCTION IF EXISTS public.resolve_login_email(TEXT);

CREATE OR REPLACE FUNCTION public.get_login_email_for_identifier(p_identifier TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_clean TEXT := TRIM(COALESCE(p_identifier, ''));
  v_email TEXT;
  v_digits TEXT;
BEGIN
  IF v_clean = '' THEN
    RETURN NULL;
  END IF;

  -- 1. Direct match in auth.users or renters by email
  IF v_clean LIKE '%@%' THEN
    SELECT email INTO v_email FROM auth.users WHERE LOWER(email) = LOWER(v_clean) LIMIT 1;
    IF v_email IS NOT NULL THEN RETURN LOWER(v_email); END IF;

    SELECT email INTO v_email FROM public.renters 
    WHERE LOWER(email) = LOWER(v_clean) AND deleted_at IS NULL
    ORDER BY is_active DESC LIMIT 1;
    IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN RETURN LOWER(v_email); END IF;

    -- Check if inverted: mobile_number column holds the email
    SELECT mobile_number INTO v_email FROM public.renters 
    WHERE LOWER(mobile_number) = LOWER(v_clean) AND deleted_at IS NULL
    ORDER BY is_active DESC LIMIT 1;
    IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN RETURN LOWER(v_email); END IF;
  END IF;

  -- 2. Digits match for mobile number
  v_digits := REGEXP_REPLACE(v_clean, '[^0-9]', '', 'g');
  IF LENGTH(v_digits) >= 10 THEN
    v_digits := RIGHT(v_digits, 10);
  END IF;

  IF LENGTH(v_digits) >= 7 THEN
    -- Match in auth.users by email containing digits or mobile metadata
    SELECT email INTO v_email FROM auth.users 
    WHERE (REGEXP_REPLACE(email, '[^0-9]', '', 'g') LIKE '%' || v_digits || '%' OR raw_user_meta_data->>'mobile' LIKE '%' || v_digits || '%')
    LIMIT 1;
    IF v_email IS NOT NULL THEN RETURN LOWER(v_email); END IF;

    -- Match in renters table by mobile_number or email digits
    SELECT 
      CASE 
        WHEN email LIKE '%@%' THEN email 
        WHEN mobile_number LIKE '%@%' THEN mobile_number 
        ELSE NULL 
      END INTO v_email
    FROM public.renters 
    WHERE (REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || v_digits || '%' OR REGEXP_REPLACE(email, '[^0-9]', '', 'g') LIKE '%' || v_digits || '%')
      AND deleted_at IS NULL
    ORDER BY is_active DESC LIMIT 1;
    
    IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN RETURN LOWER(v_email); END IF;

    -- Fallback check for generated local email
    SELECT email INTO v_email FROM auth.users 
    WHERE LOWER(email) = LOWER('tenant_' || v_digits || '@rentbill.local') LIMIT 1;
    IF v_email IS NOT NULL THEN RETURN LOWER(v_email); END IF;
  END IF;

  -- 3. Match in profiles by username or renters by name
  SELECT u.email INTO v_email FROM auth.users u
  JOIN public.profiles p ON u.id = p.id
  WHERE LOWER(p.username) = LOWER(v_clean) LIMIT 1;
  IF v_email IS NOT NULL THEN RETURN LOWER(v_email); END IF;

  SELECT 
    CASE 
      WHEN email LIKE '%@%' THEN email 
      WHEN mobile_number LIKE '%@%' THEN mobile_number 
      ELSE NULL 
    END INTO v_email
  FROM public.renters 
  WHERE LOWER(name) = LOWER(v_clean) AND deleted_at IS NULL
  ORDER BY is_active DESC LIMIT 1;
  
  IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN RETURN LOWER(v_email); END IF;

  RETURN CASE WHEN v_clean LIKE '%@%' THEN LOWER(v_clean) ELSE NULL END;
END;
$$;

CREATE OR REPLACE FUNCTION public.resolve_login_email(p_identifier TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  RETURN public.get_login_email_for_identifier(p_identifier);
END;
$$;

-- Admin List Tenants with Auth (Auto-swaps inverted email/phone)
DROP FUNCTION IF EXISTS public.admin_list_tenants_with_auth();
CREATE OR REPLACE FUNCTION public.admin_list_tenants_with_auth()
RETURNS TABLE (
  renter_id BIGINT,
  renter_name TEXT,
  mobile_number TEXT,
  email TEXT,
  unit_name TEXT,
  property_name TEXT,
  user_id UUID,
  has_auth_account BOOLEAN,
  last_sign_in_at TIMESTAMPTZ,
  is_active BOOLEAN,
  is_disabled BOOLEAN,
  assigned_password TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can view tenant credentials.';
  END IF;

  RETURN QUERY
  SELECT 
    r.id AS renter_id,
    r.name AS renter_name,
    CASE 
      WHEN r.mobile_number LIKE '%@%' AND (r.email IS NULL OR r.email NOT LIKE '%@%') THEN r.email
      ELSE r.mobile_number 
    END AS mobile_number,
    CASE 
      WHEN r.mobile_number LIKE '%@%' AND (r.email IS NULL OR r.email NOT LIKE '%@%') THEN r.mobile_number
      ELSE r.email 
    END AS email,
    u.unit_name,
    p.name AS property_name,
    r.user_id,
    (u_auth.id IS NOT NULL) AS has_auth_account,
    u_auth.last_sign_in_at,
    r.is_active,
    COALESCE(prof.is_disabled, u_auth.banned_until > NOW(), FALSE) AS is_disabled,
    COALESCE(u_auth.raw_user_meta_data->>'assigned_password', NULL) AS assigned_password
  FROM public.renters r
  LEFT JOIN public.units u ON r.unit_id = u.id
  LEFT JOIN public.properties p ON u.property_id = p.id
  LEFT JOIN auth.users u_auth ON (r.user_id = u_auth.id OR (r.email IS NOT NULL AND LOWER(r.email) = LOWER(u_auth.email)))
  LEFT JOIN public.profiles prof ON u_auth.id = prof.id
  WHERE r.deleted_at IS NULL
  ORDER BY r.is_active DESC, r.name ASC;
END;
$$;

-- Admin: Create or update a tenant login with password
DROP FUNCTION IF EXISTS public.admin_create_tenant_user(TEXT, TEXT, TEXT, BIGINT);
DROP FUNCTION IF EXISTS public.admin_create_tenant_user(TEXT, TEXT, TEXT, BIGINT, TEXT);

CREATE OR REPLACE FUNCTION public.admin_create_tenant_user(
  p_email TEXT,
  p_password TEXT,
  p_username TEXT DEFAULT NULL,
  p_renter_id BIGINT DEFAULT NULL,
  p_mobile TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
  v_user_id UUID;
  v_encrypted_pw TEXT;
  v_username TEXT;
  v_clean_mobile TEXT;
  v_renter_mobile TEXT;
  v_renter_uid UUID;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can manage tenant accounts.';
  END IF;

  p_email := LOWER(TRIM(p_email));
  IF p_email IS NULL OR p_email = '' THEN
    RAISE EXCEPTION 'A valid email address is required.';
  END IF;

  IF LENGTH(p_password) < 6 THEN
    RAISE EXCEPTION 'Password must be at least 6 characters long.';
  END IF;

  v_clean_mobile := REGEXP_REPLACE(COALESCE(p_mobile, ''), '[^0-9]', '', 'g');
  IF LENGTH(v_clean_mobile) >= 10 THEN
    v_clean_mobile := RIGHT(v_clean_mobile, 10);
  END IF;

  -- Check renters table for linked user_id or mobile number if p_renter_id is provided
  IF p_renter_id IS NOT NULL THEN
    SELECT user_id, mobile_number INTO v_renter_uid, v_renter_mobile
    FROM public.renters WHERE id = p_renter_id;
    
    IF v_renter_uid IS NOT NULL THEN
      v_user_id := v_renter_uid;
    END IF;

    IF v_clean_mobile IS NULL OR v_clean_mobile = '' THEN
      v_clean_mobile := REGEXP_REPLACE(COALESCE(v_renter_mobile, ''), '[^0-9]', '', 'g');
      IF LENGTH(v_clean_mobile) >= 10 THEN
        v_clean_mobile := RIGHT(v_clean_mobile, 10);
      END IF;
    END IF;
  END IF;

  v_username := COALESCE(NULLIF(TRIM(p_username), ''), SPLIT_PART(p_email, '@', 1));

  -- 1. Search by email if not found yet
  IF v_user_id IS NULL THEN
    SELECT id INTO v_user_id FROM auth.users WHERE LOWER(email) = p_email LIMIT 1;
  END IF;

  -- 2. Search by mobile number if not found yet
  IF v_user_id IS NULL AND LENGTH(v_clean_mobile) >= 7 THEN
    SELECT id INTO v_user_id FROM auth.users 
    WHERE (REGEXP_REPLACE(email, '[^0-9]', '', 'g') LIKE '%' || v_clean_mobile || '%' OR raw_user_meta_data->>'mobile' LIKE '%' || v_clean_mobile || '%')
    LIMIT 1;
  END IF;

  BEGIN
    v_encrypted_pw := extensions.crypt(p_password, extensions.gen_salt('bf', 10));
  EXCEPTION WHEN OTHERS THEN
    BEGIN
      v_encrypted_pw := public.crypt(p_password, public.gen_salt('bf', 10));
    EXCEPTION WHEN OTHERS THEN
      v_encrypted_pw := crypt(p_password, gen_salt('bf', 10));
    END;
  END;

  IF v_user_id IS NOT NULL THEN
    UPDATE auth.users
    SET encrypted_password = v_encrypted_pw,
        email = LOWER(p_email),
        email_confirmed_at = COALESCE(email_confirmed_at, NOW()),
        confirmed_at = COALESCE(confirmed_at, NOW()),
        banned_until = NULL,
        raw_user_meta_data = COALESCE(raw_user_meta_data, '{}'::jsonb) || jsonb_build_object(
          'role', 'TENANT',
          'username', v_username,
          'mobile', COALESCE(NULLIF(v_clean_mobile, ''), raw_user_meta_data->>'mobile'),
          'renter_id', COALESCE(p_renter_id, (raw_user_meta_data->>'renter_id')::bigint),
          'assigned_password', p_password
        ),
        updated_at = NOW()
    WHERE id = v_user_id;

    BEGIN
      UPDATE auth.identities
      SET provider_id = LOWER(p_email),
          identity_data = jsonb_build_object('sub', v_user_id::text, 'email', LOWER(p_email)),
          updated_at = NOW()
      WHERE user_id = v_user_id AND provider = 'email';
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    INSERT INTO public.profiles (id, username, email, role, is_disabled)
    VALUES (v_user_id, v_username, LOWER(p_email), 'TENANT', FALSE)
    ON CONFLICT (id) DO UPDATE SET
      role = 'TENANT',
      username = COALESCE(EXCLUDED.username, public.profiles.username),
      email = COALESCE(EXCLUDED.email, public.profiles.email),
      is_disabled = FALSE,
      updated_at = NOW();
  ELSE
    v_user_id := gen_random_uuid();

    INSERT INTO auth.users (
      id, instance_id, email, encrypted_password, email_confirmed_at, confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at, role, aud
    ) VALUES (
      v_user_id, '00000000-0000-0000-0000-000000000000', p_email, v_encrypted_pw, NOW(), NOW(),
      jsonb_build_object('provider', 'email', 'providers', jsonb_build_array('email')),
      jsonb_build_object('role', 'TENANT', 'username', v_username, 'mobile', v_clean_mobile, 'renter_id', p_renter_id, 'assigned_password', p_password),
      NOW(), NOW(), 'authenticated', 'authenticated'
    );

    BEGIN
      INSERT INTO auth.identities (
        id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
      ) VALUES (
        gen_random_uuid(), v_user_id, jsonb_build_object('sub', v_user_id::text, 'email', p_email),
        'email', p_email, NOW(), NOW(), NOW()
      );
    EXCEPTION WHEN OTHERS THEN
      NULL;
    END;

    INSERT INTO public.profiles (id, username, email, role)
    VALUES (v_user_id, v_username, p_email, 'TENANT')
    ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, role = 'TENANT';
  END IF;

  IF p_renter_id IS NOT NULL THEN
    UPDATE public.renters
    SET user_id = v_user_id, email = p_email, updated_at = NOW()
    WHERE id = p_renter_id;
  ELSE
    UPDATE public.renters
    SET user_id = v_user_id, updated_at = NOW()
    WHERE LOWER(email) = p_email AND deleted_at IS NULL;
  END IF;

  RETURN jsonb_build_object('success', true, 'user_id', v_user_id, 'email', p_email, 'username', v_username);
END;
$$;

CREATE OR REPLACE FUNCTION public.admin_create_tenant_user(
  p_email TEXT,
  p_password TEXT,
  p_username TEXT DEFAULT NULL,
  p_renter_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
BEGIN
  RETURN public.admin_create_tenant_user(p_email, p_password, p_username, p_renter_id, NULL);
END;
$$;

-- Direct Admin Tenant Password Update RPC
DROP FUNCTION IF EXISTS public.admin_update_tenant_user_password(BIGINT, TEXT);
DROP FUNCTION IF EXISTS public.admin_update_tenant_user_password(BIGINT, TEXT, TEXT);

CREATE OR REPLACE FUNCTION public.admin_update_tenant_user_password(
  p_renter_id BIGINT,
  p_new_password TEXT,
  p_email TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
  v_user_id UUID;
  v_renter_email TEXT;
  v_renter_mobile TEXT;
  v_clean_mobile TEXT;
  v_target_email TEXT;
  v_encrypted_pw TEXT;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can reset tenant passwords.';
  END IF;

  IF LENGTH(p_new_password) < 6 THEN
    RAISE EXCEPTION 'Password must be at least 6 characters long.';
  END IF;

  SELECT user_id, email, mobile_number INTO v_user_id, v_renter_email, v_renter_mobile
  FROM public.renters WHERE id = p_renter_id;

  IF p_email IS NOT NULL AND p_email LIKE '%@%' THEN
    v_target_email := LOWER(TRIM(p_email));
  ELSIF v_renter_email IS NOT NULL AND v_renter_email LIKE '%@%' THEN
    v_target_email := LOWER(TRIM(v_renter_email));
  END IF;

  v_clean_mobile := REGEXP_REPLACE(COALESCE(v_renter_mobile, ''), '[^0-9]', '', 'g');
  IF LENGTH(v_clean_mobile) >= 10 THEN
    v_clean_mobile := RIGHT(v_clean_mobile, 10);
  END IF;

  IF v_target_email IS NULL AND LENGTH(v_clean_mobile) >= 10 THEN
    v_target_email := 'tenant_' || v_clean_mobile || '@rentbill.local';
  END IF;

  IF v_user_id IS NULL AND v_target_email IS NOT NULL THEN
    SELECT id INTO v_user_id FROM auth.users WHERE LOWER(email) = v_target_email LIMIT 1;
  END IF;

  IF v_user_id IS NULL AND LENGTH(v_clean_mobile) >= 7 THEN
    SELECT id INTO v_user_id FROM auth.users 
    WHERE (REGEXP_REPLACE(email, '[^0-9]', '', 'g') LIKE '%' || v_clean_mobile || '%' OR raw_user_meta_data->>'mobile' LIKE '%' || v_clean_mobile || '%')
    LIMIT 1;
  END IF;

  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'No auth account found for tenant.');
  END IF;

  BEGIN
    v_encrypted_pw := extensions.crypt(p_new_password, extensions.gen_salt('bf', 10));
  EXCEPTION WHEN OTHERS THEN
    BEGIN
      v_encrypted_pw := public.crypt(p_new_password, public.gen_salt('bf', 10));
    EXCEPTION WHEN OTHERS THEN
      v_encrypted_pw := crypt(p_new_password, gen_salt('bf', 10));
    END;
  END;

  UPDATE auth.users
  SET encrypted_password = v_encrypted_pw,
      email = COALESCE(v_target_email, email),
      email_confirmed_at = COALESCE(email_confirmed_at, NOW()),
      confirmed_at = COALESCE(confirmed_at, NOW()),
      banned_until = NULL,
      raw_user_meta_data = COALESCE(raw_user_meta_data, '{}'::jsonb) || jsonb_build_object(
        'role', 'TENANT',
        'mobile', COALESCE(NULLIF(v_clean_mobile, ''), raw_user_meta_data->>'mobile'),
        'renter_id', p_renter_id,
        'assigned_password', p_new_password
      ),
      updated_at = NOW()
  WHERE id = v_user_id;

  BEGIN
    UPDATE auth.identities
    SET provider_id = COALESCE(v_target_email, provider_id),
        identity_data = jsonb_build_object('sub', v_user_id::text, 'email', COALESCE(v_target_email, provider_id)),
        updated_at = NOW()
    WHERE user_id = v_user_id AND provider = 'email';
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  UPDATE public.profiles
  SET is_disabled = FALSE, email = COALESCE(v_target_email, email), updated_at = NOW()
  WHERE id = v_user_id;

  UPDATE public.renters
  SET user_id = v_user_id, email = COALESCE(v_target_email, email), updated_at = NOW()
  WHERE id = p_renter_id;

  RETURN jsonb_build_object('success', true, 'user_id', v_user_id, 'email', v_target_email);
END;
$$;

-- Admin: Reset tenant password directly
DROP FUNCTION IF EXISTS public.admin_reset_tenant_password(UUID, TEXT);
CREATE OR REPLACE FUNCTION public.admin_reset_tenant_password(
  p_user_id UUID,
  p_new_password TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can reset passwords.';
  END IF;

  IF LENGTH(p_new_password) < 6 THEN
    RAISE EXCEPTION 'Password must be at least 6 characters long.';
  END IF;

  UPDATE auth.users
  SET encrypted_password = extensions.crypt(p_new_password, extensions.gen_salt('bf', 10)),
      banned_until = NULL,
      raw_user_meta_data = COALESCE(raw_user_meta_data, '{}'::jsonb) || jsonb_build_object(
        'assigned_password', p_new_password
      ),
      updated_at = NOW()
  WHERE id = p_user_id;

  UPDATE public.profiles
  SET is_disabled = FALSE, updated_at = NOW()
  WHERE id = p_user_id;

  RETURN jsonb_build_object('success', true, 'message', 'Password updated successfully');
END;
$$;

-- Admin Delete Tenant Login (Robust Foreign Key Nullification)
DROP FUNCTION IF EXISTS public.admin_delete_tenant_login(BIGINT, UUID);
CREATE OR REPLACE FUNCTION public.admin_delete_tenant_login(
  p_renter_id BIGINT,
  p_user_id UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_uid UUID := p_user_id;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can delete tenant login accounts.';
  END IF;

  IF v_uid IS NULL AND p_renter_id IS NOT NULL THEN
    SELECT user_id INTO v_uid FROM public.renters WHERE id = p_renter_id;
  END IF;

  IF p_renter_id IS NOT NULL THEN
    UPDATE public.renters SET user_id = NULL, updated_at = NOW() WHERE id = p_renter_id;
  END IF;

  IF v_uid IS NOT NULL THEN
    UPDATE public.renters SET user_id = NULL WHERE user_id = v_uid;
    UPDATE public.bills SET voided_by = NULL WHERE voided_by = v_uid;
    UPDATE public.payments SET verified_by = NULL WHERE verified_by = v_uid;
    UPDATE public.payments SET reversed_by = NULL WHERE reversed_by = v_uid;
    UPDATE public.expenses SET created_by = NULL WHERE created_by = v_uid;
    UPDATE public.owner_withdrawals SET created_by = NULL WHERE created_by = v_uid;
    UPDATE public.documents SET created_by = NULL WHERE created_by = v_uid;
    UPDATE public.maintenance_tasks SET reported_by = NULL WHERE reported_by = v_uid;

    BEGIN
      DELETE FROM auth.mfa_amr_claims WHERE session_id IN (SELECT id FROM auth.sessions WHERE user_id = v_uid);
      DELETE FROM auth.mfa_factors WHERE user_id = v_uid;
      DELETE FROM auth.sessions WHERE user_id = v_uid;
      DELETE FROM auth.refresh_tokens WHERE session_id IN (SELECT id FROM auth.sessions WHERE user_id = v_uid);
      DELETE FROM auth.identities WHERE user_id = v_uid;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    DELETE FROM public.profiles WHERE id = v_uid;

    BEGIN
      DELETE FROM auth.users WHERE id = v_uid;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END IF;

  RETURN jsonb_build_object('success', true, 'message', 'Tenant login account deleted successfully');
END;
$$;

-- Auto-link tenant own lease upon login
DROP FUNCTION IF EXISTS public.tenant_link_own_lease();
CREATE OR REPLACE FUNCTION public.tenant_link_own_lease()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_email TEXT := auth.email();
  v_digits TEXT;
  v_prof_email TEXT;
  v_meta_renter_id BIGINT;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'Unauthenticated');
  END IF;

  SELECT email INTO v_prof_email FROM public.profiles WHERE id = v_uid;
  BEGIN
    SELECT (raw_user_meta_data->>'renter_id')::BIGINT INTO v_meta_renter_id FROM auth.users WHERE id = v_uid;
  EXCEPTION WHEN OTHERS THEN
    v_meta_renter_id := NULL;
  END;

  v_digits := REGEXP_REPLACE(COALESCE(v_email, ''), '[^0-9]', '', 'g');

  UPDATE public.renters
  SET user_id = v_uid, updated_at = NOW()
  WHERE deleted_at IS NULL
    AND (
      user_id = v_uid
      OR (v_meta_renter_id IS NOT NULL AND id = v_meta_renter_id)
      OR (v_email IS NOT NULL AND v_email != '' AND LOWER(TRIM(email)) = LOWER(TRIM(v_email)))
      OR (v_prof_email IS NOT NULL AND v_prof_email != '' AND LOWER(TRIM(email)) = LOWER(TRIM(v_prof_email)))
      OR (v_email IS NOT NULL AND v_email != '' AND LOWER(TRIM(mobile_number)) = LOWER(TRIM(v_email)))
      OR (LENGTH(v_digits) >= 7 AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || v_digits || '%')
    );

  RETURN jsonb_build_object('success', true);
END;
$$;

-- 6.1 RLS ENFORCEMENT FOR PROFILES (Ensures profiles table has RLS & self-view)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins full access to profiles" ON public.profiles;
CREATE POLICY "Admins full access to profiles" ON public.profiles FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "Users view own profile" ON public.profiles;
CREATE POLICY "Users view own profile" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
DROP POLICY IF EXISTS "Users update own profile" ON public.profiles;
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- 6.2 STAFF & AUDITOR ROLE RLS POLICIES (Expands the 4-role model on existing DBs)
-- AUDITOR: read-only access to all application tables
DROP POLICY IF EXISTS "Auditors view properties" ON public.properties;
CREATE POLICY "Auditors view properties" ON public.properties FOR SELECT TO authenticated USING (public.is_auditor());
DROP POLICY IF EXISTS "Auditors view units" ON public.units;
CREATE POLICY "Auditors view units" ON public.units FOR SELECT TO authenticated USING (public.is_auditor());
DROP POLICY IF EXISTS "Auditors view renters" ON public.renters;
CREATE POLICY "Auditors view renters" ON public.renters FOR SELECT TO authenticated USING (public.is_auditor());
DROP POLICY IF EXISTS "Auditors view owners" ON public.owners;
CREATE POLICY "Auditors view owners" ON public.owners FOR SELECT TO authenticated USING (public.is_auditor());
DROP POLICY IF EXISTS "Auditors view bills" ON public.bills;
CREATE POLICY "Auditors view bills" ON public.bills FOR SELECT TO authenticated USING (public.is_auditor());
DROP POLICY IF EXISTS "Auditors view payments" ON public.payments;
CREATE POLICY "Auditors view payments" ON public.payments FOR SELECT TO authenticated USING (public.is_auditor());
DROP POLICY IF EXISTS "Auditors view expenses" ON public.expenses;
CREATE POLICY "Auditors view expenses" ON public.expenses FOR SELECT TO authenticated USING (public.is_auditor());
DROP POLICY IF EXISTS "Auditors view owner_withdrawals" ON public.owner_withdrawals;
CREATE POLICY "Auditors view owner_withdrawals" ON public.owner_withdrawals FOR SELECT TO authenticated USING (public.is_auditor());
DROP POLICY IF EXISTS "Auditors view documents" ON public.documents;
CREATE POLICY "Auditors view documents" ON public.documents FOR SELECT TO authenticated USING (public.is_auditor());
DROP POLICY IF EXISTS "Auditors view maintenance_tasks" ON public.maintenance_tasks;
CREATE POLICY "Auditors view maintenance_tasks" ON public.maintenance_tasks FOR SELECT TO authenticated USING (public.is_auditor());

-- STAFF: view properties/units/renters, and view/update maintenance work orders
DROP POLICY IF EXISTS "Staff view properties" ON public.properties;
CREATE POLICY "Staff view properties" ON public.properties FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS "Staff view units" ON public.units;
CREATE POLICY "Staff view units" ON public.units FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS "Staff view renters" ON public.renters;
CREATE POLICY "Staff view renters" ON public.renters FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS "Staff view maintenance_tasks" ON public.maintenance_tasks;
CREATE POLICY "Staff view maintenance_tasks" ON public.maintenance_tasks FOR SELECT TO authenticated USING (public.is_staff());
DROP POLICY IF EXISTS "Staff update maintenance_tasks" ON public.maintenance_tasks;
CREATE POLICY "Staff update maintenance_tasks" ON public.maintenance_tasks FOR UPDATE TO authenticated USING (public.is_staff()) WITH CHECK (public.is_staff());

-- 6.3 UNIFIED USER MANAGEMENT RPCs (All Roles)
-- These power the Settings > User Logins tab for Admin/Staff/Auditor accounts.

-- List all users (any role)
CREATE OR REPLACE FUNCTION public.admin_list_all_users()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
  v_result JSONB;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can list user accounts.';
  END IF;

  SELECT jsonb_agg(
    jsonb_build_object(
      'user_id',          p.id,
      'username',         p.username,
      'email',            p.email,
      'role',             p.role,
      'is_disabled',      COALESCE(p.is_disabled, FALSE),
      'created_at',       p.created_at,
      'updated_at',       p.updated_at,
      'last_sign_in_at',  au.last_sign_in_at,
      'email_confirmed',  (au.email_confirmed_at IS NOT NULL)
    ) ORDER BY
      CASE p.role
        WHEN 'ADMIN'   THEN 1
        WHEN 'STAFF'   THEN 2
        WHEN 'AUDITOR' THEN 3
        WHEN 'TENANT'  THEN 4
        ELSE 5
      END,
      p.username NULLS LAST
  )
  INTO v_result
  FROM public.profiles p
  LEFT JOIN auth.users au ON au.id = p.id;

  RETURN COALESCE(v_result, '[]'::jsonb);
END;
$$;

-- Create user (any non-tenant role: ADMIN / STAFF / AUDITOR)
CREATE OR REPLACE FUNCTION public.admin_create_user(
  p_email     TEXT,
  p_password  TEXT,
  p_username  TEXT DEFAULT 'New User',
  p_role      TEXT DEFAULT 'STAFF'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
  v_user_id      UUID;
  v_encrypted_pw TEXT;
  v_upper_role   TEXT;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can create user accounts.';
  END IF;

  v_upper_role := UPPER(TRIM(p_role));
  IF v_upper_role NOT IN ('ADMIN', 'STAFF', 'AUDITOR') THEN
    RAISE EXCEPTION 'Invalid role "%". Allowed roles for this function: ADMIN, STAFF, AUDITOR. Use admin_create_tenant_user for TENANT accounts.', p_role;
  END IF;

  IF p_email IS NULL OR TRIM(p_email) = '' THEN
    RAISE EXCEPTION 'Email address is required.';
  END IF;
  IF p_password IS NULL OR LENGTH(p_password) < 6 THEN
    RAISE EXCEPTION 'Password must be at least 6 characters long.';
  END IF;

  v_encrypted_pw := extensions.crypt(p_password, extensions.gen_salt('bf'));

  SELECT id INTO v_user_id FROM auth.users WHERE LOWER(email) = LOWER(TRIM(p_email));

  IF v_user_id IS NOT NULL THEN
    UPDATE auth.users
    SET encrypted_password = v_encrypted_pw,
        email_confirmed_at = COALESCE(email_confirmed_at, NOW()),
        confirmed_at       = COALESCE(confirmed_at, NOW()),
        updated_at         = NOW()
    WHERE id = v_user_id;

    INSERT INTO public.profiles (id, username, email, role, is_disabled)
    VALUES (v_user_id, p_username, LOWER(TRIM(p_email)), v_upper_role, FALSE)
    ON CONFLICT (id) DO UPDATE SET
      role = EXCLUDED.role,
      username = EXCLUDED.username,
      email = EXCLUDED.email,
      is_disabled = FALSE,
      updated_at = NOW();
  ELSE
    v_user_id := gen_random_uuid();
    INSERT INTO auth.users (
      id, instance_id, email, encrypted_password, email_confirmed_at, confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at, role, aud
    ) VALUES (
      v_user_id, '00000000-0000-0000-0000-000000000000',
      LOWER(TRIM(p_email)), v_encrypted_pw, NOW(), NOW(),
      jsonb_build_object('provider', 'email', 'providers', jsonb_build_array('email')),
      jsonb_build_object('role', v_upper_role, 'username', p_username),
      NOW(), NOW(), 'authenticated', 'authenticated'
    );

    BEGIN
      INSERT INTO auth.identities (
        id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
      ) VALUES (
        gen_random_uuid(), v_user_id,
        jsonb_build_object('sub', v_user_id::text, 'email', LOWER(TRIM(p_email))),
        'email', LOWER(TRIM(p_email)), NOW(), NOW(), NOW()
      );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    INSERT INTO public.profiles (id, username, email, role, is_disabled)
    VALUES (v_user_id, p_username, LOWER(TRIM(p_email)), v_upper_role, FALSE)
    ON CONFLICT (id) DO UPDATE SET
      role = EXCLUDED.role,
      username = EXCLUDED.username,
      email = EXCLUDED.email;
  END IF;

  RETURN jsonb_build_object('success', true, 'user_id', v_user_id, 'role', v_upper_role);
END;
$$;

-- Reset any user's password
CREATE OR REPLACE FUNCTION public.admin_update_user_password(
  p_user_id      UUID,
  p_new_password TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
  v_encrypted_pw TEXT;
  v_target_role  TEXT;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can reset user passwords.';
  END IF;
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'User ID is required.';
  END IF;
  IF p_new_password IS NULL OR LENGTH(p_new_password) < 6 THEN
    RAISE EXCEPTION 'Password must be at least 6 characters long.';
  END IF;
  IF p_user_id = auth.uid() THEN
    RAISE EXCEPTION 'Cannot reset your own password via this function. Use the Change Password form instead.';
  END IF;

  SELECT role INTO v_target_role FROM public.profiles WHERE id = p_user_id;
  IF v_target_role IS NULL THEN
    RAISE EXCEPTION 'User profile not found for the given ID.';
  END IF;

  v_encrypted_pw := extensions.crypt(p_new_password, extensions.gen_salt('bf'));

  UPDATE auth.users
  SET encrypted_password = v_encrypted_pw, updated_at = NOW()
  WHERE id = p_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Auth user not found for the given ID.';
  END IF;

  RETURN jsonb_build_object('success', true, 'user_id', p_user_id);
END;
$$;

-- Change user role
CREATE OR REPLACE FUNCTION public.admin_change_user_role(
  p_user_id  UUID,
  p_new_role TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
  v_upper_role  TEXT;
  v_current_role TEXT;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can change user roles.';
  END IF;
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'User ID is required.';
  END IF;

  v_upper_role := UPPER(TRIM(p_new_role));
  IF v_upper_role NOT IN ('ADMIN', 'TENANT', 'STAFF', 'AUDITOR') THEN
    RAISE EXCEPTION 'Invalid role "%". Allowed: ADMIN, TENANT, STAFF, AUDITOR.', p_new_role;
  END IF;
  IF p_user_id = auth.uid() THEN
    RAISE EXCEPTION 'Cannot change your own role.';
  END IF;

  SELECT role INTO v_current_role FROM public.profiles WHERE id = p_user_id;
  IF v_current_role IS NULL THEN
    RAISE EXCEPTION 'User profile not found.';
  END IF;

  UPDATE public.profiles
  SET role = v_upper_role, updated_at = NOW()
  WHERE id = p_user_id;

  UPDATE auth.users
  SET raw_user_meta_data = raw_user_meta_data || jsonb_build_object('role', v_upper_role),
      updated_at = NOW()
  WHERE id = p_user_id;

  RETURN jsonb_build_object('success', true, 'user_id', p_user_id, 'old_role', v_current_role, 'new_role', v_upper_role);
END;
$$;

-- Toggle user active/disabled status
CREATE OR REPLACE FUNCTION public.admin_toggle_user_status(
  p_user_id  UUID,
  p_disabled BOOLEAN DEFAULT TRUE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can toggle user status.';
  END IF;
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'User ID is required.';
  END IF;
  IF p_user_id = auth.uid() AND p_disabled = TRUE THEN
    RAISE EXCEPTION 'Cannot deactivate your own account.';
  END IF;

  UPDATE public.profiles
  SET is_disabled = p_disabled, updated_at = NOW()
  WHERE id = p_user_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'User profile not found.';
  END IF;

  RETURN jsonb_build_object('success', true, 'user_id', p_user_id, 'is_disabled', p_disabled);
END;
$$;

-- Delete user account (cleans up all FK references)
CREATE OR REPLACE FUNCTION public.admin_delete_user(
  p_user_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
  v_target_role TEXT;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can delete user accounts.';
  END IF;
  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'User ID is required.';
  END IF;
  IF p_user_id = auth.uid() THEN
    RAISE EXCEPTION 'Cannot delete your own account.';
  END IF;

  SELECT role INTO v_target_role FROM public.profiles WHERE id = p_user_id;
  IF v_target_role IS NULL THEN
    RAISE EXCEPTION 'User profile not found.';
  END IF;

  UPDATE public.renters SET user_id = NULL WHERE user_id = p_user_id;
  UPDATE public.bills SET voided_by = NULL WHERE voided_by = p_user_id;
  UPDATE public.payments SET verified_by = NULL WHERE verified_by = p_user_id;
  UPDATE public.payments SET reversed_by = NULL WHERE reversed_by = p_user_id;
  UPDATE public.expenses SET created_by = NULL WHERE created_by = p_user_id;
  UPDATE public.owner_withdrawals SET created_by = NULL WHERE created_by = p_user_id;
  UPDATE public.documents SET created_by = NULL WHERE created_by = p_user_id;
  UPDATE public.maintenance_tasks SET reported_by = NULL WHERE reported_by = p_user_id;

  BEGIN
    DELETE FROM auth.mfa_amr_claims WHERE session_id IN (SELECT id FROM auth.sessions WHERE user_id = p_user_id);
    DELETE FROM auth.mfa_factors WHERE user_id = p_user_id;
    DELETE FROM auth.sessions WHERE user_id = p_user_id;
    DELETE FROM auth.refresh_tokens WHERE session_id IN (SELECT id FROM auth.sessions WHERE user_id = p_user_id);
    DELETE FROM auth.identities WHERE user_id = p_user_id;
  EXCEPTION WHEN OTHERS THEN NULL;
  END;

  DELETE FROM public.profiles WHERE id = p_user_id;
  DELETE FROM auth.users WHERE id = p_user_id;

  RETURN jsonb_build_object('success', true, 'deleted_user_id', p_user_id, 'deleted_role', v_target_role);
END;
$$;

-- 6.6 LEDGER & FINANCIAL RECONCILIATION
-- A virtual double-entry-style ledger derived live from the source tables.
-- Because the app uses soft deletes (deleted_at) and derived caches, the
-- account balances are computed directly from source rows on read so they can
-- NEVER drift from actual transactions. This gives an exact auditable
-- "billed vs collected vs spent" reconciliation.
--
-- Account map (signed so the ledger balances):
--   RECEIVABLE_INVOICED     (+) billed      bills net_amount (non-voided)
--   RECEIVABLE_WRITTEN_OFF  (-) writeoff    bills write_off_amount
--   CASH_IN                 (+) received    verified rent payments
--   CASH_OUT_EXPENSES       (-) paid        operating expenses
--   CASH_OUT_WITHDRAWALS    (-) paid        owner withdrawals
-- ============================================================================

CREATE OR REPLACE VIEW public.v_ledger_entries AS
SELECT
  'BILL'::text AS source_type,
  b.id AS source_id,
  b.renter_id,
  'RECEIVABLE_INVOICED'::text AS account,
  b.billing_period AS period,
  b.bill_date AS entry_date,
  b.net_amount AS amount
FROM public.bills b
WHERE b.deleted_at IS NULL
  AND b.status != 'VOID'
  AND b.voided_at IS NULL
UNION ALL
SELECT
  'BILL_WRITE_OFF'::text,
  b.id, b.renter_id,
  'RECEIVABLE_WRITTEN_OFF'::text,
  b.billing_period, b.bill_date,
  -(COALESCE(b.write_off_amount, 0))
FROM public.bills b
WHERE b.deleted_at IS NULL
  AND b.status != 'VOID'
  AND b.voided_at IS NULL
  AND COALESCE(b.write_off_amount, 0) <> 0
UNION ALL
SELECT
  'PAYMENT'::text,
  p.id, p.renter_id,
  'CASH_IN'::text,
  b.billing_period, p.payment_date,
  p.amount
FROM public.payments p
JOIN public.bills b ON b.id = p.bill_id
WHERE p.deleted_at IS NULL
  AND p.reversed_at IS NULL
  AND (p.proof_status IS NULL OR p.proof_status IN ('NONE', 'VERIFIED'))
UNION ALL
SELECT
  'EXPENSE'::text,
  e.id, NULL::bigint,
  'CASH_OUT_EXPENSES'::text,
  to_char(e.date, 'YYYY-MM'), e.date,
  e.amount
FROM public.expenses e
WHERE e.deleted_at IS NULL
UNION ALL
SELECT
  'WITHDRAWAL'::text,
  w.id, NULL::bigint,
  'CASH_OUT_WITHDRAWALS'::text,
  to_char(w.date, 'YYYY-MM'), w.date,
  w.amount
FROM public.owner_withdrawals w
WHERE w.deleted_at IS NULL;

CREATE OR REPLACE VIEW public.v_ledger_accounts AS
SELECT
  account,
  period,
  COUNT(*) AS entries,
  SUM(amount) AS balance,
  SUM(amount) FILTER (WHERE amount >= 0) AS debit_total,
  SUM(amount) FILTER (WHERE amount < 0) AS credit_total
FROM public.v_ledger_entries
GROUP BY account, period;

CREATE OR REPLACE FUNCTION public.fn_reconcile_ledger()
RETURNS jsonb
LANGUAGE sql
STABLE
SET search_path = public
AS $$
  WITH totals AS (
    SELECT
      COALESCE(SUM(amount) FILTER (WHERE account = 'RECEIVABLE_INVOICED'), 0)      AS total_billed,
      COALESCE(SUM(amount) FILTER (WHERE account = 'RECEIVABLE_WRITTEN_OFF'), 0)   AS total_written_off,
      COALESCE(SUM(amount) FILTER (WHERE account = 'CASH_IN'), 0)                  AS total_collected,
      COALESCE(SUM(amount) FILTER (WHERE account = 'CASH_OUT_EXPENSES'), 0)        AS total_expenses,
      COALESCE(SUM(amount) FILTER (WHERE account = 'CASH_OUT_WITHDRAWALS'), 0)     AS total_withdrawn
    FROM public.v_ledger_entries
  ),
  per_bill AS (
    SELECT
      b.id,
      b.net_amount,
      COALESCE(b.write_off_amount, 0) AS written_off,
      COALESCE(SUM(p.amount), 0) AS collected
    FROM public.bills b
    LEFT JOIN public.payments p
      ON p.bill_id = b.id
      AND p.deleted_at IS NULL
      AND p.reversed_at IS NULL
      AND (p.proof_status IS NULL OR p.proof_status IN ('NONE', 'VERIFIED'))
    WHERE b.deleted_at IS NULL
      AND b.status != 'VOID'
      AND b.voided_at IS NULL
    GROUP BY b.id, b.net_amount, b.write_off_amount
  ),
  bill_snapshot AS (
    SELECT
      SUM(net_amount) AS billed,
      SUM(written_off) AS written_off,
      SUM(collected) AS collected,
      SUM(net_amount) - SUM(written_off) - SUM(collected) AS outstanding
    FROM per_bill
  ),
  calcs AS (
    SELECT
      t.total_billed,
      t.total_written_off,
      t.total_collected,
      t.total_expenses,
      t.total_withdrawn,
      bs.billed AS per_bill_billed,
      bs.written_off AS per_bill_written_off,
      bs.collected AS per_bill_collected,
      bs.outstanding AS outstanding,
      (t.total_billed + t.total_written_off) - t.total_collected AS net_receivable,
      t.total_collected - (t.total_expenses + t.total_withdrawn) AS net_cash_flow
    FROM totals t, bill_snapshot bs
  )
  SELECT jsonb_build_object(
    'total_billed',            calcs.total_billed,
    'total_written_off',       calcs.total_written_off,
    'total_collected',         calcs.total_collected,
    'total_expenses',          calcs.total_expenses,
    'total_withdrawn',         calcs.total_withdrawn,
    'outstanding',             calcs.outstanding,
    'net_receivable',          calcs.net_receivable,
    'net_cash_flow',           calcs.net_cash_flow,
    'accounts', (
      SELECT jsonb_object_agg(account, balance) FROM public.v_ledger_accounts
    ),
    'integrity'::text, jsonb_build_object(
      'billed_matches',        calcs.total_billed = calcs.per_bill_billed,
      'collected_matches',     calcs.total_collected = calcs.per_bill_collected,
      'written_off_matches',   calcs.total_written_off = calcs.per_bill_written_off,
      'outstanding_non_negative', calcs.outstanding >= 0
    )
  )
  FROM calcs;
$$;

-- 7. Grant execution permissions
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.is_auditor() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.is_staff() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.get_login_email_for_identifier(TEXT) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.resolve_login_email(TEXT) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.admin_list_tenants_with_auth() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_tenant_user(TEXT, TEXT, TEXT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_tenant_user(TEXT, TEXT, TEXT, BIGINT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_tenant_user_password(BIGINT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_reset_tenant_password(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_tenant_login(BIGINT, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_toggle_tenant_login_status(BIGINT, UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tenant_link_own_lease() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_list_all_users() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_user(TEXT, TEXT, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_update_user_password(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_change_user_role(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_toggle_user_status(UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_user(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.fn_reconcile_ledger() TO authenticated;
GRANT SELECT ON public.v_ledger_entries TO authenticated;
GRANT SELECT ON public.v_ledger_accounts TO authenticated;

-- 8. Default Administrator Account (idempotent — only created if missing)
-- Customize the email/password below before running on a fresh database.
DO $$
DECLARE
  v_admin_id UUID := gen_random_uuid();
  v_admin_email TEXT := 'admin@jai.com';       -- Change to your preferred admin email
  v_admin_password TEXT := 'Admin@123';         -- Change to your preferred admin password
  v_encrypted_pw TEXT;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE LOWER(email) = LOWER(v_admin_email)) THEN
    v_encrypted_pw := extensions.crypt(v_admin_password, extensions.gen_salt('bf'));

    INSERT INTO auth.users (
      id, instance_id, email, encrypted_password, email_confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at, role, aud
    ) VALUES (
      v_admin_id, '00000000-0000-0000-0000-000000000000', v_admin_email, v_encrypted_pw, NOW(),
      jsonb_build_object('provider', 'email', 'providers', jsonb_build_array('email')),
      jsonb_build_object('role', 'ADMIN', 'username', 'Admin'),
      NOW(), NOW(), 'authenticated', 'authenticated'
    );

    BEGIN
      INSERT INTO auth.identities (
        id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
      ) VALUES (
        gen_random_uuid(), v_admin_id, jsonb_build_object('sub', v_admin_id::text, 'email', v_admin_email),
        'email', v_admin_email, NOW(), NOW(), NOW()
      );
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    INSERT INTO public.profiles (id, username, email, role)
    VALUES (v_admin_id, 'Admin', v_admin_email, 'ADMIN')
    ON CONFLICT (id) DO UPDATE SET role = 'ADMIN';
  ELSE
    UPDATE public.profiles
    SET role = 'ADMIN'
    WHERE LOWER(email) = LOWER(v_admin_email);
  END IF;
END $$;
