-- ============================================================================
-- RentBill Pro — Master Database Schema (Single-User Architecture)
-- Production PostgreSQL Schema for Supabase
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- 1. USER PROFILES & AUTH SIGNUP TRIGGER
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT,
    email TEXT,
    role TEXT NOT NULL DEFAULT 'ADMIN' CHECK (role IN ('ADMIN', 'STAFF', 'AUDITOR', 'TENANT')),
    is_disabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  BEGIN
    INSERT INTO public.profiles (id, username, email, role)
    VALUES (
      NEW.id,
      COALESCE(NEW.raw_user_meta_data->>'username', SPLIT_PART(NEW.email, '@', 1)),
      NEW.email,
      COALESCE(NEW.raw_user_meta_data->>'role', 'ADMIN')
    )
    ON CONFLICT (id) DO UPDATE 
      SET email = EXCLUDED.email,
          updated_at = NOW();
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================================
-- 2. OWNERS TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.owners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    name TEXT NOT NULL UNIQUE,
    email TEXT,
    mobile_number TEXT,
    upi_id TEXT,
    bank_name TEXT,
    account_number TEXT,
    ifsc_code TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- ============================================================================
-- 3. PROPERTIES & UNITS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    name TEXT NOT NULL UNIQUE,
    address TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    property_id BIGINT NOT NULL REFERENCES public.properties(id) ON DELETE RESTRICT,
    unit_number TEXT NOT NULL,
    unit_name TEXT,
    floor INTEGER DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'VACANT' CHECK (status IN ('VACANT', 'OCCUPIED', 'MAINTENANCE')),
    monthly_rent BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    UNIQUE(property_id, unit_number)
);

-- ============================================================================
-- 4. RENTERS (TENANT MANAGEMENT DIRECTORY)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.renters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    unit_id BIGINT NOT NULL REFERENCES public.units(id) ON DELETE RESTRICT,
    owner_id BIGINT REFERENCES public.owners(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    mobile_number TEXT,
    email TEXT,
    aadhar_number TEXT,
    base_rent BIGINT NOT NULL DEFAULT 0,
    advance_amount BIGINT NOT NULL DEFAULT 0,
    pending_arrears BIGINT NOT NULL DEFAULT 0,
    maint_charge BIGINT NOT NULL DEFAULT 0,
    eb_per_unit_price NUMERIC(10, 2) NOT NULL DEFAULT 8.00,
    initial_eb_reading BIGINT NOT NULL DEFAULT 0,
    water_calc_mode TEXT NOT NULL DEFAULT 'FIXED' CHECK (water_calc_mode IN ('FIXED', 'METERED')),
    water_fixed_charge BIGINT NOT NULL DEFAULT 150,
    water_per_unit_price NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    initial_water_reading BIGINT NOT NULL DEFAULT 0,
    agreement_start_date DATE,
    agreement_expiry_date DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_renters_unit_id ON public.renters(unit_id);
CREATE INDEX IF NOT EXISTS idx_renters_owner_id ON public.renters(owner_id);
CREATE INDEX IF NOT EXISTS idx_renters_user_id ON public.renters(user_id);
CREATE INDEX IF NOT EXISTS idx_renters_mobile ON public.renters(mobile_number);

-- ============================================================================
-- 5. BILLS (INVOICES & REVENUE CLAIMS)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    renter_id BIGINT NOT NULL REFERENCES public.renters(id) ON DELETE RESTRICT,
    billing_period TEXT NOT NULL,
    period_start_date DATE,
    period_end_date DATE,
    bill_date DATE DEFAULT CURRENT_DATE,
    due_date DATE,
    rent_amount BIGINT NOT NULL DEFAULT 0,
    maint_amount BIGINT NOT NULL DEFAULT 0,
    prev_eb_reading BIGINT NOT NULL DEFAULT 0,
    curr_eb_reading BIGINT NOT NULL DEFAULT 0,
    eb_units BIGINT NOT NULL DEFAULT 0,
    eb_rate NUMERIC(10, 2) NOT NULL DEFAULT 8.00,
    eb_amount BIGINT NOT NULL DEFAULT 0,
    water_calc_mode TEXT NOT NULL DEFAULT 'FIXED' CHECK (water_calc_mode IN ('FIXED', 'METERED')),
    prev_water_reading BIGINT NOT NULL DEFAULT 0,
    curr_water_reading BIGINT NOT NULL DEFAULT 0,
    water_units BIGINT NOT NULL DEFAULT 0,
    water_rate NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    water_amount BIGINT NOT NULL DEFAULT 0,
    arrears_included BIGINT NOT NULL DEFAULT 0,
    late_fee BIGINT NOT NULL DEFAULT 0,
    others BIGINT NOT NULL DEFAULT 0,
    gross_amount BIGINT NOT NULL DEFAULT 0,
    discount_amount BIGINT NOT NULL DEFAULT 0,
    net_amount BIGINT NOT NULL DEFAULT 0,
    paid_amount BIGINT NOT NULL DEFAULT 0,
    write_off_amount BIGINT NOT NULL DEFAULT 0,
    write_off_reason TEXT,
    status TEXT NOT NULL DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID', 'OVERDUE', 'VOID')),
    payment_method TEXT,
    payment_details TEXT,
    proof_status TEXT NOT NULL DEFAULT 'NONE' CHECK (proof_status IN ('NONE', 'PENDING', 'VERIFIED', 'REJECTED')),
    proof_ref TEXT,
    proof_photo TEXT,
    proof_date TIMESTAMPTZ,
    notes TEXT,
    voided_at TIMESTAMPTZ,
    voided_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    void_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    UNIQUE(renter_id, billing_period)
);

CREATE INDEX IF NOT EXISTS idx_bills_renter_id ON public.bills(renter_id);
CREATE INDEX IF NOT EXISTS idx_bills_status ON public.bills(status);
CREATE INDEX IF NOT EXISTS idx_bills_due_date ON public.bills(due_date);

-- Trigger: Automatic Financial Bill Calculation
CREATE OR REPLACE FUNCTION public.calculate_bill_amounts()
RETURNS TRIGGER AS $$
BEGIN
  NEW.gross_amount := COALESCE(NEW.rent_amount, 0) + 
                      COALESCE(NEW.maint_amount, 0) + 
                      COALESCE(NEW.eb_amount, 0) + 
                      COALESCE(NEW.water_amount, 0) + 
                      COALESCE(NEW.arrears_included, 0) + 
                      COALESCE(NEW.late_fee, 0) + 
                      COALESCE(NEW.others, 0);

  NEW.net_amount := GREATEST(0, NEW.gross_amount - COALESCE(NEW.discount_amount, 0));

  IF NEW.status != 'VOID' THEN
    IF NEW.paid_amount >= NEW.net_amount AND NEW.net_amount > 0 THEN
      NEW.status := 'PAID';
    ELSIF NEW.paid_amount > 0 THEN
      NEW.status := 'PARTIAL';
    ELSE
      NEW.status := 'UNPAID';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_calculate_bill_amounts ON public.bills;
CREATE TRIGGER trg_calculate_bill_amounts
  BEFORE INSERT OR UPDATE ON public.bills
  FOR EACH ROW EXECUTE FUNCTION public.calculate_bill_amounts();

-- ============================================================================
-- 6. PAYMENTS (CASH INFLOWS & AUDIT LOGS)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    bill_id BIGINT NOT NULL REFERENCES public.bills(id) ON DELETE RESTRICT,
    renter_id BIGINT NOT NULL REFERENCES public.renters(id) ON DELETE RESTRICT,
    amount BIGINT NOT NULL,
    payment_method TEXT,
    transaction_reference TEXT,
    payment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    proof_status TEXT NOT NULL DEFAULT 'NONE' CHECK (proof_status IN ('NONE', 'PENDING', 'VERIFIED', 'REJECTED')),
    proof_photo TEXT,
    verified_at TIMESTAMPTZ,
    verified_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    reversed_at TIMESTAMPTZ,
    reversed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    reversal_reason TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_payments_bill_id ON public.payments(bill_id);
CREATE INDEX IF NOT EXISTS idx_payments_renter_id ON public.payments(renter_id);
CREATE INDEX IF NOT EXISTS idx_payments_date ON public.payments(payment_date);

-- Trigger: Synchronize Bill Paid Amount & Status
CREATE OR REPLACE FUNCTION public.sync_bill_paid_amount()
RETURNS TRIGGER AS $$
DECLARE
  v_bill_id BIGINT;
  v_total_paid BIGINT;
  v_net_amount BIGINT;
  v_bill_status TEXT;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_bill_id := OLD.bill_id;
  ELSE
    v_bill_id := NEW.bill_id;
  END IF;

  SELECT COALESCE(SUM(amount), 0) INTO v_total_paid
  FROM public.payments
  WHERE bill_id = v_bill_id
    AND deleted_at IS NULL
    AND reversed_at IS NULL
    AND (proof_status IS NULL OR proof_status IN ('NONE', 'VERIFIED'));

  SELECT net_amount, status INTO v_net_amount, v_bill_status
  FROM public.bills
  WHERE id = v_bill_id;

  IF v_bill_status != 'VOID' THEN
    IF v_total_paid >= v_net_amount AND v_net_amount > 0 THEN
      v_bill_status := 'PAID';
    ELSIF v_total_paid > 0 THEN
      v_bill_status := 'PARTIAL';
    ELSE
      v_bill_status := 'UNPAID';
    END IF;

    UPDATE public.bills
    SET paid_amount = v_total_paid,
        status = v_bill_status,
        updated_at = NOW()
    WHERE id = v_bill_id;
  ELSE
    UPDATE public.bills
    SET paid_amount = v_total_paid,
        updated_at = NOW()
    WHERE id = v_bill_id;
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_sync_bill_paid_amount ON public.payments;
CREATE TRIGGER trg_sync_bill_paid_amount
  AFTER INSERT OR UPDATE OR DELETE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.sync_bill_paid_amount();

-- ============================================================================
-- 7. EXPENSES, WITHDRAWALS, MAINTENANCE & DOCUMENTS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    property_id BIGINT REFERENCES public.properties(id) ON DELETE SET NULL,
    category TEXT NOT NULL,
    amount BIGINT NOT NULL,
    expense_date DATE NOT NULL DEFAULT CURRENT_DATE,
    description TEXT,
    receipt_photo TEXT,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.owner_withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    owner_id BIGINT NOT NULL REFERENCES public.owners(id) ON DELETE RESTRICT,
    property_id BIGINT REFERENCES public.properties(id) ON DELETE SET NULL,
    amount BIGINT NOT NULL,
    withdrawal_date DATE NOT NULL DEFAULT CURRENT_DATE,
    payment_method TEXT,
    transaction_ref TEXT,
    notes TEXT,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.maintenance_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    property_id BIGINT REFERENCES public.properties(id) ON DELETE SET NULL,
    unit_id BIGINT REFERENCES public.units(id) ON DELETE SET NULL,
    renter_id BIGINT REFERENCES public.renters(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    description TEXT,
    priority TEXT NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'EMERGENCY')),
    status TEXT NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    estimated_cost BIGINT DEFAULT 0,
    actual_cost BIGINT DEFAULT 0,
    reported_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    assigned_to TEXT,
    due_date DATE,
    completed_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    entity_type TEXT NOT NULL CHECK (entity_type IN ('PROPERTY', 'UNIT', 'RENTER', 'OWNER', 'GENERAL')),
    entity_id BIGINT,
    document_name TEXT NOT NULL,
    category TEXT NOT NULL CHECK (category IN ('LEASE_AGREEMENT', 'IDENTITY_PROOF', 'PROPERTY_TAX', 'OWNERSHIP_DEED', 'MAINTENANCE', 'ELECTRICITY_DEED', 'OTHER')),
    file_path TEXT NOT NULL,
    file_size INTEGER,
    mime_type TEXT,
    expiry_date DATE,
    notes TEXT,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- ============================================================================
-- 8. SAFE USER DELETION TRIGGERS (SUPABASE DASHBOARD INTEGRATION)
-- ============================================================================

-- Nullifies references when a profile is removed
CREATE OR REPLACE FUNCTION public.handle_profile_before_delete()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.renters SET user_id = NULL WHERE user_id = OLD.id;
  UPDATE public.bills SET voided_by = NULL WHERE voided_by = OLD.id;
  UPDATE public.payments SET verified_by = NULL WHERE verified_by = OLD.id;
  UPDATE public.payments SET reversed_by = NULL WHERE reversed_by = OLD.id;
  UPDATE public.expenses SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.owner_withdrawals SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.documents SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.maintenance_tasks SET reported_by = NULL WHERE reported_by = OLD.id;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_handle_profile_before_delete ON public.profiles;
CREATE TRIGGER trg_handle_profile_before_delete
  BEFORE DELETE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.handle_profile_before_delete();

-- Fires when a user is deleted from Supabase Dashboard (Authentication > Users)
CREATE OR REPLACE FUNCTION public.handle_auth_user_before_delete()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE public.renters SET user_id = NULL WHERE user_id = OLD.id;
  UPDATE public.bills SET voided_by = NULL WHERE voided_by = OLD.id;
  UPDATE public.payments SET verified_by = NULL WHERE verified_by = OLD.id;
  UPDATE public.payments SET reversed_by = NULL WHERE reversed_by = OLD.id;
  UPDATE public.expenses SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.owner_withdrawals SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.documents SET created_by = NULL WHERE created_by = OLD.id;
  UPDATE public.maintenance_tasks SET reported_by = NULL WHERE reported_by = OLD.id;

  BEGIN
    UPDATE storage.objects SET owner = NULL WHERE owner = OLD.id;
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  DELETE FROM public.profiles WHERE id = OLD.id;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_deleted ON auth.users;
CREATE TRIGGER on_auth_user_deleted
  BEFORE DELETE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_auth_user_before_delete();

-- ============================================================================
-- 9. STORAGE BUCKET FOR PROOFS & ATTACHMENTS
-- ============================================================================

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'storage' AND table_name = 'buckets') THEN
    INSERT INTO storage.buckets (id, name, public) 
    VALUES ('proofs', 'proofs', true)
    ON CONFLICT (id) DO NOTHING;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'storage' AND table_name = 'objects') THEN
    EXECUTE 'CREATE POLICY "Authenticated upload proofs" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = ''proofs'');';
    EXECUTE 'CREATE POLICY "Authenticated view proofs" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = ''proofs'');';
  END IF;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN undefined_table THEN NULL;
END $$;

-- ============================================================================
-- 10. ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owner_withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  IF auth.uid() IS NULL THEN RETURN FALSE; END IF;
  RETURN COALESCE((SELECT role = 'ADMIN' FROM public.profiles WHERE id = auth.uid()), FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

CREATE POLICY "Authenticated full access to profiles" ON public.profiles FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access to owners" ON public.owners FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access to properties" ON public.properties FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access to units" ON public.units FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access to renters" ON public.renters FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access to bills" ON public.bills FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access to payments" ON public.payments FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access to expenses" ON public.expenses FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access to owner_withdrawals" ON public.owner_withdrawals FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access to maintenance_tasks" ON public.maintenance_tasks FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE POLICY "Authenticated full access to documents" ON public.documents FOR ALL TO authenticated USING (true) WITH CHECK (true);
CREATE OR REPLACE FUNCTION public.resolve_login_email(p_identifier TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_clean TEXT := TRIM(COALESCE(p_identifier, ''));
  v_email TEXT;
BEGIN
  IF v_clean = '' THEN
    RETURN NULL;
  END IF;

  -- 1. If identifier is already an email, return as-is
  IF v_clean LIKE '%@%' THEN
    RETURN LOWER(v_clean);
  END IF;

  -- 2. Lookup by username in public.profiles (case-insensitive)
  SELECT email INTO v_email
  FROM public.profiles
  WHERE LOWER(username) = LOWER(v_clean)
  LIMIT 1;

  IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN
    RETURN LOWER(v_email);
  END IF;

  -- 3. Lookup in auth.users by raw_user_meta_data->>'username'
  SELECT email INTO v_email
  FROM auth.users
  WHERE LOWER(COALESCE(raw_user_meta_data->>'username', '')) = LOWER(v_clean)
  LIMIT 1;

  IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN
    RETURN LOWER(v_email);
  END IF;

  -- 4. Fallback lookup by renter name
  SELECT email INTO v_email
  FROM public.renters
  WHERE LOWER(name) = LOWER(v_clean)
    AND deleted_at IS NULL
  ORDER BY is_active DESC
  LIMIT 1;

  RETURN LOWER(v_email);
END;
$$;

-- ============================================================================
-- 11. EXPLICIT GRANTS
-- ============================================================================

GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;
GRANT EXECUTE ON FUNCTION public.resolve_login_email(TEXT) TO authenticated, anon;

-- ============================================================================
-- 12. DEFAULT ADMIN PROFILE SETUP (IF USERS ALREADY EXIST)
-- ============================================================================

DO $$
DECLARE
  v_first_user_id UUID;
BEGIN
  SELECT id INTO v_first_user_id FROM auth.users ORDER BY created_at ASC LIMIT 1;
  IF v_first_user_id IS NOT NULL THEN
    INSERT INTO public.profiles (id, username, email, role)
    SELECT id, SPLIT_PART(email, '@', 1), email, 'ADMIN'
    FROM auth.users
    WHERE id = v_first_user_id
    ON CONFLICT (id) DO UPDATE SET role = 'ADMIN';
  END IF;
END $$;
