-- ============================================================================
-- RENTBILL PRO — COMPLETE MASTER SUPABASE POSTGRESQL SCHEMA
-- Target Database: Supabase Cloud PostgreSQL
-- Paste directly into Supabase SQL Editor:
-- https://supabase.com/dashboard/project/_/sql
-- ============================================================================

-- Enable required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ============================================================================
-- 1. USER PROFILES & AUTH SIGNUP TRIGGER
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    username TEXT UNIQUE NOT NULL,
    email TEXT,
    role TEXT NOT NULL DEFAULT 'TENANT' CHECK (role IN ('ADMIN', 'TENANT', 'STAFF', 'AUDITOR')),
    is_disabled BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  BEGIN
    INSERT INTO public.profiles (id, username, email, role)
    VALUES (
      NEW.id,
      COALESCE(NEW.raw_user_meta_data->>'username', SPLIT_PART(NEW.email, '@', 1)),
      NEW.email,
      COALESCE(NEW.raw_user_meta_data->>'role', 'TENANT')
    )
    ON CONFLICT (id) DO UPDATE 
      SET email = EXCLUDED.email,
          updated_at = NOW();
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  BEGIN
    UPDATE public.renters
    SET user_id = NEW.id,
        updated_at = NOW()
    WHERE (LOWER(email) = LOWER(NEW.email) OR user_id = NEW.id)
      AND deleted_at IS NULL;
  EXCEPTION WHEN OTHERS THEN
    NULL;
  END;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============================================================================
-- 2. OWNERS TABLE (WITH BANK DETAILS & UPI)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.owners (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    name TEXT NOT NULL UNIQUE,
    email TEXT,
    mobile_number TEXT,
    upi_id TEXT,
    bank_name TEXT,
    account_number TEXT,
    ifsc_code TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- ============================================================================
-- 3. PROPERTIES & RENTAL UNITS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.properties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    name TEXT NOT NULL,
    address TEXT,
    owner_name TEXT,
    agreement_terms TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    property_id BIGINT NOT NULL REFERENCES public.properties(id) ON DELETE RESTRICT,
    unit_name TEXT NOT NULL,
    floor TEXT,
    default_rent BIGINT NOT NULL DEFAULT 0,
    default_maint BIGINT NOT NULL DEFAULT 0,
    agreement_terms TEXT,
    status TEXT NOT NULL DEFAULT 'VACANT' CHECK (status IN ('VACANT', 'OCCUPIED', 'RESERVED', 'MAINTENANCE')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    UNIQUE(property_id, unit_name)
);

-- ============================================================================
-- 4. RENTERS (TENANTS WITH ASSIGNED OWNER)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.renters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    unit_id BIGINT NOT NULL REFERENCES public.units(id) ON DELETE RESTRICT,
    owner_id BIGINT REFERENCES public.owners(id) ON DELETE SET NULL,
    owner_name TEXT,
    user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    mobile_number TEXT,
    email TEXT,
    aadhar_no TEXT,
    perm_address TEXT,
    emergency_contact TEXT,
    occupation TEXT,
    move_in_date DATE,
    advance_amount BIGINT NOT NULL DEFAULT 0,
    base_rent BIGINT NOT NULL DEFAULT 0,
    eb_unit_price BIGINT NOT NULL DEFAULT 0,
    maint_charge BIGINT NOT NULL DEFAULT 0,
    water_calc_mode TEXT NOT NULL DEFAULT 'FIXED' CHECK (water_calc_mode IN ('FIXED', 'METERED')),
    water_fixed_charge BIGINT NOT NULL DEFAULT 0,
    water_unit_price BIGINT NOT NULL DEFAULT 0,
    initial_eb BIGINT NOT NULL DEFAULT 0,
    initial_water BIGINT NOT NULL DEFAULT 0,
    pending_arrears BIGINT NOT NULL DEFAULT 0,
    assigned_upi TEXT,
    co_tenant_names TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    vacate_date DATE,
    exit_reason TEXT,
    agreement_start_date DATE,
    agreement_expiry_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- ============================================================================
-- 5. BILLS & PAYMENTS (WITH AUTOMATED FINANCIAL GUARD TRIGGER)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    renter_id BIGINT NOT NULL REFERENCES public.renters(id) ON DELETE RESTRICT,
    billing_period TEXT NOT NULL, -- Format: YYYY-MM
    period_start_date DATE,       -- Exact stay period from date (e.g. 2026-09-01)
    period_end_date DATE,         -- Exact stay period to date (e.g. 2026-09-30)
    bill_date DATE DEFAULT CURRENT_DATE, -- Date invoice was generated
    due_date DATE,                -- Payment due date
    prev_eb_reading BIGINT NOT NULL DEFAULT 0,
    curr_eb_reading BIGINT,
    eb_unit_price BIGINT NOT NULL DEFAULT 0,
    eb_amount BIGINT NOT NULL DEFAULT 0,
    prev_water_reading BIGINT NOT NULL DEFAULT 0,
    curr_water_reading BIGINT,
    water_unit_price BIGINT NOT NULL DEFAULT 0,
    water_calc_mode TEXT NOT NULL DEFAULT 'FIXED',
    water_amount BIGINT NOT NULL DEFAULT 0,
    rent_amount BIGINT NOT NULL DEFAULT 0,
    maint_amount BIGINT NOT NULL DEFAULT 0,
    others BIGINT NOT NULL DEFAULT 0,
    arrears_included BIGINT NOT NULL DEFAULT 0,
    late_fee BIGINT NOT NULL DEFAULT 0,
    discount_amount BIGINT NOT NULL DEFAULT 0,
    write_off_amount BIGINT NOT NULL DEFAULT 0,
    gross_amount BIGINT NOT NULL DEFAULT 0,
    net_amount BIGINT NOT NULL DEFAULT 0,
    paid_amount BIGINT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID', 'OVERPAID', 'VOID')),
    payment_date DATE,
    payment_method TEXT,
    payment_details TEXT,
    proof_status TEXT NOT NULL DEFAULT 'NONE' CHECK (proof_status IN ('NONE', 'PENDING', 'VERIFIED', 'REJECTED')),
    proof_ref TEXT,
    proof_photo TEXT,
    proof_date TIMESTAMPTZ,
    notes TEXT,
    voided_at TIMESTAMPTZ,
    voided_by UUID REFERENCES public.profiles(id),
    void_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    UNIQUE(renter_id, billing_period)
);

ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS period_start_date DATE;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS period_end_date DATE;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS bill_date DATE DEFAULT CURRENT_DATE;
ALTER TABLE public.bills ADD COLUMN IF NOT EXISTS due_date DATE;

-- Financial Calculation Guard Trigger for Bills
CREATE OR REPLACE FUNCTION public.calculate_bill_amounts()
RETURNS TRIGGER AS $$
BEGIN
  -- Compute gross amount in paise
  NEW.gross_amount := COALESCE(NEW.rent_amount, 0) + 
                      COALESCE(NEW.maint_amount, 0) + 
                      COALESCE(NEW.eb_amount, 0) + 
                      COALESCE(NEW.water_amount, 0) + 
                      COALESCE(NEW.arrears_included, 0) + 
                      COALESCE(NEW.late_fee, 0) + 
                      COALESCE(NEW.others, 0);
  
  -- Compute net amount after discount
  NEW.net_amount := GREATEST(0, NEW.gross_amount - COALESCE(NEW.discount_amount, 0));

  -- Update bill status automatically based on paid_amount vs net_amount
  IF NEW.status != 'VOID' THEN
    IF NEW.paid_amount >= NEW.net_amount AND NEW.net_amount > 0 THEN
      NEW.status := 'PAID';
    ELSIF NEW.paid_amount > 0 THEN
      NEW.status := 'PARTIAL';
    ELSIF NEW.status != 'VOID' THEN
      NEW.status := 'UNPAID';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER trg_calculate_bill_amounts
  BEFORE INSERT OR UPDATE ON public.bills
  FOR EACH ROW EXECUTE FUNCTION public.calculate_bill_amounts();

CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    bill_id BIGINT NOT NULL REFERENCES public.bills(id) ON DELETE RESTRICT,
    renter_id BIGINT NOT NULL REFERENCES public.renters(id) ON DELETE RESTRICT,
    amount BIGINT NOT NULL,
    payment_method TEXT,
    transaction_reference TEXT,
    payment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    proof_status TEXT NOT NULL DEFAULT 'NONE' CHECK (proof_status IN ('NONE', 'PENDING', 'VERIFIED', 'REJECTED')),
    proof_photo TEXT,
    verified_at TIMESTAMPTZ,
    verified_by UUID REFERENCES public.profiles(id),
    reversed_at TIMESTAMPTZ,
    reversed_by UUID REFERENCES public.profiles(id),
    reversal_reason TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- Financial Synchronization Trigger
CREATE OR REPLACE FUNCTION public.sync_bill_paid_amount()
RETURNS TRIGGER AS $$
DECLARE
  v_bill_id BIGINT;
  v_total_paid BIGINT;
BEGIN
  v_bill_id := COALESCE(NEW.bill_id, OLD.bill_id);
  
  IF v_bill_id IS NOT NULL THEN
    SELECT COALESCE(SUM(amount), 0) INTO v_total_paid
    FROM public.payments
    WHERE bill_id = v_bill_id
      AND (proof_status IS NULL OR proof_status != 'REJECTED')
      AND reversed_at IS NULL
      AND deleted_at IS NULL;
    
    UPDATE public.bills
    SET paid_amount = v_total_paid,
        updated_at = NOW()
    WHERE id = v_bill_id;
  END IF;
  
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER trg_sync_bill_paid_amount
  AFTER INSERT OR UPDATE OR DELETE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.sync_bill_paid_amount();

-- ============================================================================
-- 6. OPERATING EXPENSES & OWNER WITHDRAWALS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    category TEXT NOT NULL,
    amount BIGINT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    notes TEXT,
    owner_name TEXT,
    created_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.owner_withdrawals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    owner_name TEXT NOT NULL,
    amount BIGINT NOT NULL,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    notes TEXT,
    created_by UUID REFERENCES public.profiles(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    title TEXT NOT NULL,
    category TEXT NOT NULL DEFAULT 'DEED',
    entity_type TEXT DEFAULT 'GENERAL',
    entity_id TEXT,
    file_url TEXT,
    expiry_date DATE,
    notes TEXT,
    created_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 6. Maintenance & Repair Work Orders Table
CREATE TABLE IF NOT EXISTS public.maintenance_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL DEFAULT 'PLUMBING' CHECK (category IN ('PLUMBING', 'ELECTRICAL', 'APPLIANCE', 'CLEANING', 'PAINTING', 'CARPENTRY', 'GENERAL', 'OTHER')),
    priority TEXT NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    property_id BIGINT REFERENCES public.properties(id) ON DELETE SET NULL,
    unit_id BIGINT REFERENCES public.units(id) ON DELETE SET NULL,
    renter_id BIGINT REFERENCES public.renters(id) ON DELETE SET NULL,
    reported_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    assigned_to TEXT,
    estimated_cost BIGINT DEFAULT 0,
    actual_cost BIGINT DEFAULT 0,
    scheduled_date DATE,
    completed_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- ============================================================================
-- 7. PERFORMANCE INDEXES
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_properties_deleted ON public.properties(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_units_deleted ON public.units(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_renters_deleted ON public.renters(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_bills_deleted ON public.bills(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_payments_deleted ON public.payments(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_expenses_deleted ON public.expenses(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_withdrawals_deleted ON public.owner_withdrawals(deleted_at) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_documents_deleted ON public.documents(deleted_at) WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_renters_unit ON public.renters(unit_id);
CREATE INDEX IF NOT EXISTS idx_renters_owner ON public.renters(owner_id);
CREATE INDEX IF NOT EXISTS idx_renters_user_id ON public.renters(user_id);
CREATE INDEX IF NOT EXISTS idx_renters_mobile ON public.renters(mobile_number);
CREATE INDEX IF NOT EXISTS idx_renters_email ON public.renters(email);

CREATE INDEX IF NOT EXISTS idx_bills_renter ON public.bills(renter_id);
CREATE INDEX IF NOT EXISTS idx_bills_billing_period ON public.bills(billing_period);
CREATE INDEX IF NOT EXISTS idx_bills_status ON public.bills(status);

CREATE INDEX IF NOT EXISTS idx_payments_bill ON public.payments(bill_id);
CREATE INDEX IF NOT EXISTS idx_payments_renter ON public.payments(renter_id);
CREATE INDEX IF NOT EXISTS idx_payments_date ON public.payments(payment_date);

CREATE INDEX IF NOT EXISTS idx_expenses_date ON public.expenses(date);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON public.profiles(role);

-- ============================================================================
-- 8. ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owner_withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
DECLARE
  v_role TEXT;
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN FALSE;
  END IF;

  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();

  RETURN COALESCE(v_role = 'ADMIN', FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 8.1 PROFILES POLICIES
CREATE POLICY "Admins full access to profiles" ON public.profiles FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Users view own profile" ON public.profiles FOR SELECT TO authenticated USING (auth.uid() = id);
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- 8.2 OWNERS POLICIES (Landlord bank details protected)
CREATE POLICY "Admins full access to owners" ON public.owners FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Tenants view assigned owner" ON public.owners FOR SELECT TO authenticated USING (
  id IN (
    SELECT owner_id FROM public.renters 
    WHERE (user_id = auth.uid() OR (email IS NOT NULL AND LOWER(email) = LOWER(auth.email())))
      AND deleted_at IS NULL
  )
);

-- 8.3 PROPERTIES & UNITS POLICIES
CREATE POLICY "Admins full access to properties" ON public.properties FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Tenants view property" ON public.properties FOR SELECT TO authenticated USING (
  id IN (
    SELECT u.property_id FROM public.units u
    JOIN public.renters r ON r.unit_id = u.id
    WHERE (r.user_id = auth.uid() OR (r.email IS NOT NULL AND LOWER(r.email) = LOWER(auth.email())))
      AND r.deleted_at IS NULL
  )
);

CREATE POLICY "Admins full access to units" ON public.units FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Tenants view assigned unit" ON public.units FOR SELECT TO authenticated USING (
  id IN (
    SELECT unit_id FROM public.renters 
    WHERE (user_id = auth.uid() OR (email IS NOT NULL AND LOWER(email) = LOWER(auth.email())))
      AND deleted_at IS NULL
  )
);

-- 8.4 RENTERS POLICIES
CREATE POLICY "Admins full access to renters" ON public.renters FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Tenants view own lease" ON public.renters FOR SELECT TO authenticated USING (
  (
    user_id = auth.uid() 
    OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
    OR (
      LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
      AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
    )
  )
  AND deleted_at IS NULL
);

-- 8.5 BILLS POLICIES (Strict Invoice Isolation & Soft Delete Respect)
CREATE POLICY "Admins full access to bills" ON public.bills FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Tenants view own bills" ON public.bills FOR SELECT TO authenticated USING (
  renter_id IN (
    SELECT id FROM public.renters 
    WHERE (
      user_id = auth.uid() 
      OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
      OR (
        LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
        AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
      )
    )
    AND deleted_at IS NULL
  )
  AND deleted_at IS NULL
);

-- 8.6 PAYMENTS POLICIES (Receipts & Optional Proof Submission)
CREATE POLICY "Admins full access to payments" ON public.payments FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Tenants view own payments" ON public.payments FOR SELECT TO authenticated USING (
  renter_id IN (
    SELECT id FROM public.renters 
    WHERE (
      user_id = auth.uid() 
      OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
      OR (
        LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
        AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
      )
    )
    AND deleted_at IS NULL
  )
  AND deleted_at IS NULL
);
CREATE POLICY "Tenants submit payment proof" ON public.payments FOR INSERT TO authenticated WITH CHECK (
  proof_status = 'PENDING' AND
  renter_id IN (
    SELECT id FROM public.renters 
    WHERE (
      user_id = auth.uid() 
      OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
      OR (
        LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
        AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
      )
    )
    AND deleted_at IS NULL
  )
);

-- 8.7 EXPENSES, WITHDRAWALS & DOCUMENTS (Landlord Eyes Only)
CREATE POLICY "Admins full access to expenses" ON public.expenses FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins full access to withdrawals" ON public.owner_withdrawals FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Admins full access to documents" ON public.documents FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

-- 8.8 MAINTENANCE TASKS POLICIES
ALTER TABLE public.maintenance_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins full access to maintenance_tasks" ON public.maintenance_tasks FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY "Tenants view own maintenance_tasks" ON public.maintenance_tasks FOR SELECT TO authenticated USING (
  (
    reported_by = auth.uid()
    OR renter_id IN (
      SELECT id FROM public.renters 
      WHERE (
        user_id = auth.uid() 
        OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
        OR (
          LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
          AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
        )
      )
      AND deleted_at IS NULL
    )
  )
  AND deleted_at IS NULL
);
CREATE POLICY "Tenants submit maintenance_tasks" ON public.maintenance_tasks FOR INSERT TO authenticated WITH CHECK (
  reported_by = auth.uid() OR
  renter_id IN (
    SELECT id FROM public.renters 
    WHERE (
      user_id = auth.uid() 
      OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
      OR (
        LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
        AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
      )
    )
    AND deleted_at IS NULL
  )
);

-- ============================================================================
-- DYNAMIC FOREIGN KEY CONSTRAINT MIGRATION (ON DELETE SET NULL)
-- ============================================================================
DO $$
BEGIN
  ALTER TABLE public.bills DROP CONSTRAINT IF EXISTS bills_voided_by_fkey;
  ALTER TABLE public.bills ADD CONSTRAINT bills_voided_by_fkey FOREIGN KEY (voided_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_verified_by_fkey;
  ALTER TABLE public.payments ADD CONSTRAINT payments_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id) ON DELETE SET NULL;
  
  ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_reversed_by_fkey;
  ALTER TABLE public.payments ADD CONSTRAINT payments_reversed_by_fkey FOREIGN KEY (reversed_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.expenses DROP CONSTRAINT IF EXISTS expenses_created_by_fkey;
  ALTER TABLE public.expenses ADD CONSTRAINT expenses_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.owner_withdrawals DROP CONSTRAINT IF EXISTS owner_withdrawals_created_by_fkey;
  ALTER TABLE public.owner_withdrawals ADD CONSTRAINT owner_withdrawals_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.documents DROP CONSTRAINT IF EXISTS documents_created_by_fkey;
  ALTER TABLE public.documents ADD CONSTRAINT documents_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- ============================================================================
-- 9. STORAGE BUCKET FOR PROOFS & ATTACHMENTS
-- ============================================================================

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'storage' AND table_name = 'buckets') THEN
    INSERT INTO storage.buckets (id, name, public) 
    VALUES ('proofs', 'proofs', true)
    ON CONFLICT (id) DO NOTHING;
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'storage' AND table_name = 'objects') THEN
    EXECUTE 'CREATE POLICY "Authenticated upload proofs" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = ''proofs'');';
    EXECUTE 'CREATE POLICY "Authenticated view proofs" ON storage.objects FOR SELECT TO authenticated USING (bucket_id = ''proofs'');';
  END IF;
EXCEPTION
  WHEN duplicate_object THEN NULL;
  WHEN undefined_table THEN NULL;
END $$;

-- ============================================================================
-- 10. ADMIN TENANT AUTHENTICATION & PASSWORD MANAGEMENT RPCs
-- ============================================================================

-- 10.1 Resolve user identifier (email, mobile, username) for universal tenant login
DROP FUNCTION IF EXISTS public.get_login_email_for_identifier(TEXT);
DROP FUNCTION IF EXISTS public.resolve_login_email(TEXT);

CREATE OR REPLACE FUNCTION public.get_login_email_for_identifier(p_identifier TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_clean TEXT := TRIM(COALESCE(p_identifier, ''));
  v_email TEXT;
  v_digits TEXT;
BEGIN
  IF v_clean = '' THEN
    RETURN NULL;
  END IF;

  -- 1. Direct match in auth.users or renters by email
  IF v_clean LIKE '%@%' THEN
    SELECT email INTO v_email FROM auth.users WHERE LOWER(email) = LOWER(v_clean) LIMIT 1;
    IF v_email IS NOT NULL THEN RETURN LOWER(v_email); END IF;

    SELECT email INTO v_email FROM public.renters 
    WHERE LOWER(email) = LOWER(v_clean) AND deleted_at IS NULL
    ORDER BY is_active DESC LIMIT 1;
    IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN RETURN LOWER(v_email); END IF;

    -- Check if inverted: mobile_number column holds the email
    SELECT mobile_number INTO v_email FROM public.renters 
    WHERE LOWER(mobile_number) = LOWER(v_clean) AND deleted_at IS NULL
    ORDER BY is_active DESC LIMIT 1;
    IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN RETURN LOWER(v_email); END IF;
  END IF;

  -- 2. Digits match for mobile number
  v_digits := REGEXP_REPLACE(v_clean, '[^0-9]', '', 'g');
  IF LENGTH(v_digits) >= 7 THEN
    -- Match in auth.users by email containing digits or mobile metadata
    SELECT email INTO v_email FROM auth.users 
    WHERE (REGEXP_REPLACE(email, '[^0-9]', '', 'g') LIKE '%' || v_digits || '%' OR raw_user_meta_data->>'mobile' LIKE '%' || v_digits || '%')
    LIMIT 1;
    IF v_email IS NOT NULL THEN RETURN LOWER(v_email); END IF;

    -- Match in renters table by mobile_number or email digits
    SELECT 
      CASE 
        WHEN email LIKE '%@%' THEN email 
        WHEN mobile_number LIKE '%@%' THEN mobile_number 
        ELSE NULL 
      END INTO v_email
    FROM public.renters 
    WHERE (REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || v_digits || '%' OR REGEXP_REPLACE(email, '[^0-9]', '', 'g') LIKE '%' || v_digits || '%')
      AND deleted_at IS NULL
    ORDER BY is_active DESC LIMIT 1;
    
    IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN RETURN LOWER(v_email); END IF;

    -- Fallback check for generated local email
    SELECT email INTO v_email FROM auth.users 
    WHERE LOWER(email) = LOWER('tenant_' || v_digits || '@rentbill.local') LIMIT 1;
    IF v_email IS NOT NULL THEN RETURN LOWER(v_email); END IF;
  END IF;

  -- 3. Match in profiles by username or renters by name
  SELECT u.email INTO v_email FROM auth.users u
  JOIN public.profiles p ON u.id = p.id
  WHERE LOWER(p.username) = LOWER(v_clean) LIMIT 1;
  IF v_email IS NOT NULL THEN RETURN LOWER(v_email); END IF;

  SELECT 
    CASE 
      WHEN email LIKE '%@%' THEN email 
      WHEN mobile_number LIKE '%@%' THEN mobile_number 
      ELSE NULL 
    END INTO v_email
  FROM public.renters 
  WHERE LOWER(name) = LOWER(v_clean) AND deleted_at IS NULL
  ORDER BY is_active DESC LIMIT 1;
  
  IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN RETURN LOWER(v_email); END IF;

  RETURN CASE WHEN v_clean LIKE '%@%' THEN LOWER(v_clean) ELSE NULL END;
END;
$$;

CREATE OR REPLACE FUNCTION public.resolve_login_email(p_identifier TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  RETURN public.get_login_email_for_identifier(p_identifier);
END;
$$;

-- 10.2 List all tenants with login account status
DROP FUNCTION IF EXISTS public.admin_list_tenants_with_auth();
CREATE OR REPLACE FUNCTION public.admin_list_tenants_with_auth()
RETURNS TABLE (
  renter_id BIGINT,
  renter_name TEXT,
  mobile_number TEXT,
  email TEXT,
  unit_name TEXT,
  property_name TEXT,
  user_id UUID,
  has_auth_account BOOLEAN,
  last_sign_in_at TIMESTAMPTZ,
  is_active BOOLEAN,
  is_disabled BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can view tenant credentials.';
  END IF;

  RETURN QUERY
  SELECT 
    r.id AS renter_id,
    r.name AS renter_name,
    CASE 
      WHEN r.mobile_number LIKE '%@%' AND (r.email IS NULL OR r.email NOT LIKE '%@%') THEN r.email
      ELSE r.mobile_number 
    END AS mobile_number,
    CASE 
      WHEN r.mobile_number LIKE '%@%' AND (r.email IS NULL OR r.email NOT LIKE '%@%') THEN r.mobile_number
      ELSE r.email 
    END AS email,
    u.unit_name,
    p.name AS property_name,
    r.user_id,
    (u_auth.id IS NOT NULL) AS has_auth_account,
    u_auth.last_sign_in_at,
    r.is_active,
    COALESCE(prof.is_disabled, u_auth.banned_until > NOW(), FALSE) AS is_disabled
  FROM public.renters r
  LEFT JOIN public.units u ON r.unit_id = u.id
  LEFT JOIN public.properties p ON u.property_id = p.id
  LEFT JOIN auth.users u_auth ON (r.user_id = u_auth.id OR (r.email IS NOT NULL AND LOWER(r.email) = LOWER(u_auth.email)))
  LEFT JOIN public.profiles prof ON u_auth.id = prof.id
  WHERE r.deleted_at IS NULL
  ORDER BY r.is_active DESC, r.name ASC;
END;
$$;

-- 10.3 Create or update a tenant login with password
DROP FUNCTION IF EXISTS public.admin_create_tenant_user(TEXT, TEXT, TEXT, BIGINT);
CREATE OR REPLACE FUNCTION public.admin_create_tenant_user(
  p_email TEXT,
  p_password TEXT,
  p_username TEXT DEFAULT NULL,
  p_renter_id BIGINT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
DECLARE
  v_user_id UUID;
  v_encrypted_pw TEXT;
  v_username TEXT;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can manage tenant accounts.';
  END IF;

  p_email := LOWER(TRIM(p_email));
  IF p_email IS NULL OR p_email = '' THEN
    RAISE EXCEPTION 'A valid email address is required.';
  END IF;

  IF LENGTH(p_password) < 6 THEN
    RAISE EXCEPTION 'Password must be at least 6 characters long.';
  END IF;

  v_username := COALESCE(NULLIF(TRIM(p_username), ''), SPLIT_PART(p_email, '@', 1));
  SELECT id INTO v_user_id FROM auth.users WHERE LOWER(email) = p_email;
  v_encrypted_pw := extensions.crypt(p_password, extensions.gen_salt('bf'));

  IF v_user_id IS NOT NULL THEN
    UPDATE auth.users
    SET encrypted_password = v_encrypted_pw,
        email_confirmed_at = COALESCE(email_confirmed_at, NOW()),
        updated_at = NOW()
    WHERE id = v_user_id;

    INSERT INTO public.profiles (id, username, email, role)
    VALUES (v_user_id, v_username, p_email, 'TENANT')
    ON CONFLICT (id) DO UPDATE SET
      role = 'TENANT',
      username = COALESCE(EXCLUDED.username, public.profiles.username),
      email = COALESCE(EXCLUDED.email, public.profiles.email),
      updated_at = NOW();
  ELSE
    v_user_id := gen_random_uuid();

    INSERT INTO auth.users (
      id, instance_id, email, encrypted_password, email_confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at, role, aud
    ) VALUES (
      v_user_id, '00000000-0000-0000-0000-000000000000', p_email, v_encrypted_pw, NOW(),
      jsonb_build_object('provider', 'email', 'providers', jsonb_build_array('email')),
      jsonb_build_object('role', 'TENANT', 'username', v_username),
      NOW(), NOW(), 'authenticated', 'authenticated'
    );

    BEGIN
      INSERT INTO auth.identities (
        id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
      ) VALUES (
        gen_random_uuid(), v_user_id, jsonb_build_object('sub', v_user_id::text, 'email', p_email),
        'email', p_email, NOW(), NOW(), NOW()
      );
    EXCEPTION WHEN OTHERS THEN
      NULL;
    END;

    INSERT INTO public.profiles (id, username, email, role)
    VALUES (v_user_id, v_username, p_email, 'TENANT')
    ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, role = 'TENANT';
  END IF;

  IF p_renter_id IS NOT NULL THEN
    UPDATE public.renters
    SET user_id = v_user_id, email = p_email, updated_at = NOW()
    WHERE id = p_renter_id;
  ELSE
    UPDATE public.renters
    SET user_id = v_user_id, updated_at = NOW()
    WHERE LOWER(email) = p_email AND deleted_at IS NULL;
  END IF;

  RETURN jsonb_build_object('success', true, 'user_id', v_user_id, 'email', p_email, 'username', v_username);
END;
$$;

-- 10.4 Reset tenant password directly
DROP FUNCTION IF EXISTS public.admin_reset_tenant_password(UUID, TEXT);
CREATE OR REPLACE FUNCTION public.admin_reset_tenant_password(
  p_user_id UUID,
  p_new_password TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, extensions
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can reset passwords.';
  END IF;

  IF LENGTH(p_new_password) < 6 THEN
    RAISE EXCEPTION 'Password must be at least 6 characters long.';
  END IF;

  UPDATE auth.users
  SET encrypted_password = extensions.crypt(p_new_password, extensions.gen_salt('bf')),
      updated_at = NOW()
  WHERE id = p_user_id;

  RETURN jsonb_build_object('success', true, 'message', 'Password updated successfully');
END;
$$;

-- 10.5 Delete / Revoke tenant portal login account
DROP FUNCTION IF EXISTS public.admin_delete_tenant_login(BIGINT, UUID);
CREATE OR REPLACE FUNCTION public.admin_delete_tenant_login(
  p_renter_id BIGINT,
  p_user_id UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_uid UUID := p_user_id;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can delete tenant login accounts.';
  END IF;

  IF v_uid IS NULL AND p_renter_id IS NOT NULL THEN
    SELECT user_id INTO v_uid FROM public.renters WHERE id = p_renter_id;
  END IF;

  IF p_renter_id IS NOT NULL THEN
    UPDATE public.renters
    SET user_id = NULL, updated_at = NOW()
    WHERE id = p_renter_id;
  END IF;

  IF v_uid IS NOT NULL THEN
    -- Nullify foreign key references across business tables before deletion
    UPDATE public.renters SET user_id = NULL WHERE user_id = v_uid;
    UPDATE public.bills SET voided_by = NULL WHERE voided_by = v_uid;
    UPDATE public.payments SET verified_by = NULL WHERE verified_by = v_uid;
    UPDATE public.payments SET reversed_by = NULL WHERE reversed_by = v_uid;
    UPDATE public.expenses SET created_by = NULL WHERE created_by = v_uid;
    UPDATE public.owner_withdrawals SET created_by = NULL WHERE created_by = v_uid;
    UPDATE public.documents SET created_by = NULL WHERE created_by = v_uid;

    -- Delete auth identities & session data
    BEGIN
      DELETE FROM auth.mfa_amr_claims WHERE session_id IN (SELECT id FROM auth.sessions WHERE user_id = v_uid);
      DELETE FROM auth.mfa_factors WHERE user_id = v_uid;
      DELETE FROM auth.sessions WHERE user_id = v_uid;
      DELETE FROM auth.refresh_tokens WHERE session_id IN (SELECT id FROM auth.sessions WHERE user_id = v_uid);
      DELETE FROM auth.identities WHERE user_id = v_uid;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    DELETE FROM public.profiles WHERE id = v_uid;

    BEGIN
      DELETE FROM auth.users WHERE id = v_uid;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END IF;

  RETURN jsonb_build_object('success', true, 'message', 'Tenant login account deleted successfully');
END;
$$;

-- 10.6 Deactivate / Reactivate tenant portal login access
DROP FUNCTION IF EXISTS public.admin_toggle_tenant_login_status(BIGINT, UUID, BOOLEAN);
CREATE OR REPLACE FUNCTION public.admin_toggle_tenant_login_status(
  p_renter_id BIGINT,
  p_user_id UUID DEFAULT NULL,
  p_disabled BOOLEAN DEFAULT TRUE
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_uid UUID := p_user_id;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can toggle tenant login status.';
  END IF;

  IF v_uid IS NULL AND p_renter_id IS NOT NULL THEN
    SELECT user_id INTO v_uid FROM public.renters WHERE id = p_renter_id;
  END IF;

  IF v_uid IS NOT NULL THEN
    UPDATE public.profiles
    SET is_disabled = p_disabled, updated_at = NOW()
    WHERE id = v_uid;

    IF p_disabled THEN
      UPDATE auth.users SET banned_until = '2099-01-01 00:00:00+00' WHERE id = v_uid;
    ELSE
      UPDATE auth.users SET banned_until = NULL WHERE id = v_uid;
    END IF;
  END IF;

  RETURN jsonb_build_object('success', true, 'is_disabled', p_disabled);
END;
$$;

-- 10.7 Auto-link tenant own lease upon login
DROP FUNCTION IF EXISTS public.tenant_link_own_lease();
CREATE OR REPLACE FUNCTION public.tenant_link_own_lease()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_email TEXT := auth.email();
  v_digits TEXT;
  v_prof_email TEXT;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'Unauthenticated');
  END IF;

  SELECT email INTO v_prof_email FROM public.profiles WHERE id = v_uid;
  v_digits := REGEXP_REPLACE(COALESCE(v_email, ''), '[^0-9]', '', 'g');

  UPDATE public.renters
  SET user_id = v_uid, updated_at = NOW()
  WHERE deleted_at IS NULL
    AND (
      user_id = v_uid
      OR (v_email IS NOT NULL AND v_email != '' AND LOWER(TRIM(email)) = LOWER(TRIM(v_email)))
      OR (v_prof_email IS NOT NULL AND v_prof_email != '' AND LOWER(TRIM(email)) = LOWER(TRIM(v_prof_email)))
      OR (LENGTH(v_digits) >= 7 AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || v_digits || '%')
    );

  RETURN jsonb_build_object('success', true);
END;
$$;

-- 10.8 Explicit Execution Permissions
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.get_login_email_for_identifier(TEXT) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.resolve_login_email(TEXT) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.admin_list_tenants_with_auth() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_tenant_user(TEXT, TEXT, TEXT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_reset_tenant_password(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_tenant_login(BIGINT, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_toggle_tenant_login_status(BIGINT, UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tenant_link_own_lease() TO authenticated;

-- ============================================================================
-- 11. DEFAULT ADMIN USER CREATION (CUSTOMIZABLE)
-- ============================================================================
-- You can customize your default admin login credentials below:
-- Default Email:    admin@rentbill.com
-- Default Password: Admin@123
-- ============================================================================

DO $$
DECLARE
  v_admin_id UUID := gen_random_uuid();
  v_admin_email TEXT := 'admin@jai.com'; -- Change to your preferred admin email
  v_admin_password TEXT := 'Admin@123';    -- Change to your preferred admin password
  v_encrypted_pw TEXT;
BEGIN
  -- Check if user already exists
  IF NOT EXISTS (SELECT 1 FROM auth.users WHERE LOWER(email) = LOWER(v_admin_email)) THEN
    v_encrypted_pw := extensions.crypt(v_admin_password, extensions.gen_salt('bf'));

    INSERT INTO auth.users (
      id, instance_id, email, encrypted_password, email_confirmed_at,
      raw_app_meta_data, raw_user_meta_data, created_at, updated_at, role, aud
    ) VALUES (
      v_admin_id, '00000000-0000-0000-0000-000000000000', v_admin_email, v_encrypted_pw, NOW(),
      jsonb_build_object('provider', 'email', 'providers', jsonb_build_array('email')),
      jsonb_build_object('role', 'ADMIN', 'username', 'Admin'),
      NOW(), NOW(), 'authenticated', 'authenticated'
    );

    BEGIN
      INSERT INTO auth.identities (
        id, user_id, identity_data, provider, provider_id, last_sign_in_at, created_at, updated_at
      ) VALUES (
        gen_random_uuid(), v_admin_id, jsonb_build_object('sub', v_admin_id::text, 'email', v_admin_email),
        'email', v_admin_email, NOW(), NOW(), NOW()
      );
    EXCEPTION WHEN OTHERS THEN
      NULL;
    END;

    INSERT INTO public.profiles (id, username, email, role)
    VALUES (v_admin_id, 'Admin', v_admin_email, 'ADMIN')
    ON CONFLICT (id) DO UPDATE SET role = 'ADMIN';
  ELSE
    -- If user exists, ensure they have the ADMIN role
    UPDATE public.profiles
    SET role = 'ADMIN'
    WHERE LOWER(email) = LOWER(v_admin_email);
  END IF;
END $$;
