-- ============================================================================
-- MODULE 04: BILLS & PAYMENTS (WITH FINANCIAL TRIGGERS)
-- ============================================================================

-- 1. Bills Table (With Stay Period & Meter Readings)
CREATE TABLE IF NOT EXISTS public.bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    renter_id BIGINT NOT NULL REFERENCES public.renters(id) ON DELETE RESTRICT,
    billing_period TEXT NOT NULL, -- Format: YYYY-MM
    period_start_date DATE,       -- Exact stay period start date
    period_end_date DATE,         -- Exact stay period end date
    bill_date DATE DEFAULT CURRENT_DATE, -- Date bill was generated
    due_date DATE,                -- Payment due date
    prev_eb_reading BIGINT NOT NULL DEFAULT 0,
    curr_eb_reading BIGINT,
    eb_unit_price BIGINT NOT NULL DEFAULT 0,
    eb_amount BIGINT NOT NULL DEFAULT 0,
    prev_water_reading BIGINT NOT NULL DEFAULT 0,
    curr_water_reading BIGINT,
    water_unit_price BIGINT NOT NULL DEFAULT 0,
    water_calc_mode TEXT NOT NULL DEFAULT 'FIXED',
    water_amount BIGINT NOT NULL DEFAULT 0,
    rent_amount BIGINT NOT NULL DEFAULT 0,
    maint_amount BIGINT NOT NULL DEFAULT 0,
    others BIGINT NOT NULL DEFAULT 0,
    arrears_included BIGINT NOT NULL DEFAULT 0,
    late_fee BIGINT NOT NULL DEFAULT 0,
    discount_amount BIGINT NOT NULL DEFAULT 0,
    write_off_amount BIGINT NOT NULL DEFAULT 0,
    gross_amount BIGINT NOT NULL DEFAULT 0,
    net_amount BIGINT NOT NULL DEFAULT 0,
    paid_amount BIGINT NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'UNPAID' CHECK (status IN ('UNPAID', 'PARTIAL', 'PAID', 'OVERPAID', 'VOID')),
    payment_date DATE,
    payment_method TEXT,
    payment_details TEXT,
    proof_status TEXT NOT NULL DEFAULT 'NONE' CHECK (proof_status IN ('NONE', 'PENDING', 'VERIFIED', 'REJECTED')),
    proof_ref TEXT,
    proof_photo TEXT,
    proof_date TIMESTAMPTZ,
    notes TEXT,
    voided_at TIMESTAMPTZ,
    voided_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    void_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    UNIQUE(renter_id, billing_period)
);

-- 2. Financial Calculation Guard Trigger for Bills
CREATE OR REPLACE FUNCTION public.calculate_bill_amounts()
RETURNS TRIGGER AS $$
BEGIN
  -- Compute gross amount in paise
  NEW.gross_amount := COALESCE(NEW.rent_amount, 0) + 
                      COALESCE(NEW.maint_amount, 0) + 
                      COALESCE(NEW.eb_amount, 0) + 
                      COALESCE(NEW.water_amount, 0) + 
                      COALESCE(NEW.arrears_included, 0) + 
                      COALESCE(NEW.late_fee, 0) + 
                      COALESCE(NEW.others, 0);
  
  -- Compute net amount after discount
  NEW.net_amount := GREATEST(0, NEW.gross_amount - COALESCE(NEW.discount_amount, 0));

  -- Update bill status automatically based on paid_amount vs net_amount
  IF NEW.status != 'VOID' THEN
    IF NEW.paid_amount >= NEW.net_amount AND NEW.net_amount > 0 THEN
      NEW.status := 'PAID';
    ELSIF NEW.paid_amount > 0 THEN
      NEW.status := 'PARTIAL';
    ELSIF NEW.status != 'VOID' THEN
      NEW.status := 'UNPAID';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER trg_calculate_bill_amounts
  BEFORE INSERT OR UPDATE ON public.bills
  FOR EACH ROW EXECUTE FUNCTION public.calculate_bill_amounts();

-- 3. Payments Table (Receipts & Verifications)
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    bill_id BIGINT NOT NULL REFERENCES public.bills(id) ON DELETE RESTRICT,
    renter_id BIGINT NOT NULL REFERENCES public.renters(id) ON DELETE RESTRICT,
    amount BIGINT NOT NULL,
    payment_method TEXT,
    transaction_reference TEXT,
    payment_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    proof_status TEXT NOT NULL DEFAULT 'NONE' CHECK (proof_status IN ('NONE', 'PENDING', 'VERIFIED', 'REJECTED')),
    proof_photo TEXT,
    verified_at TIMESTAMPTZ,
    verified_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    reversed_at TIMESTAMPTZ,
    reversed_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    reversal_reason TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- 4. Financial Sync Trigger for Payments
CREATE OR REPLACE FUNCTION public.sync_bill_paid_amount()
RETURNS TRIGGER AS $$
DECLARE
  v_bill_id BIGINT;
  v_total_paid BIGINT;
BEGIN
  v_bill_id := COALESCE(NEW.bill_id, OLD.bill_id);
  
  IF v_bill_id IS NOT NULL THEN
    SELECT COALESCE(SUM(amount), 0) INTO v_total_paid
    FROM public.payments
    WHERE bill_id = v_bill_id
      AND (proof_status IS NULL OR proof_status != 'REJECTED')
      AND reversed_at IS NULL
      AND deleted_at IS NULL;
    
    UPDATE public.bills
    SET paid_amount = v_total_paid,
        updated_at = NOW()
    WHERE id = v_bill_id;
  END IF;
  
  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER trg_sync_bill_paid_amount
  AFTER INSERT OR UPDATE OR DELETE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.sync_bill_paid_amount();
