-- ============================================================================
-- MODULE 12: MAINTENANCE TASKS, WORK ORDERS & REPAIRS
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.maintenance_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL DEFAULT 'PLUMBING' CHECK (category IN ('PLUMBING', 'ELECTRICAL', 'APPLIANCE', 'CLEANING', 'PAINTING', 'CARPENTRY', 'GENERAL', 'OTHER')),
    priority TEXT NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    property_id BIGINT REFERENCES public.properties(id) ON DELETE SET NULL,
    unit_id BIGINT REFERENCES public.units(id) ON DELETE SET NULL,
    renter_id BIGINT REFERENCES public.renters(id) ON DELETE SET NULL,
    reported_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    assigned_to TEXT,
    estimated_cost BIGINT DEFAULT 0,
    actual_cost BIGINT DEFAULT 0,
    scheduled_date DATE,
    completed_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- Indexing for performance
CREATE INDEX IF NOT EXISTS idx_maint_property ON public.maintenance_tasks(property_id);
CREATE INDEX IF NOT EXISTS idx_maint_unit ON public.maintenance_tasks(unit_id);
CREATE INDEX IF NOT EXISTS idx_maint_renter ON public.maintenance_tasks(renter_id);
CREATE INDEX IF NOT EXISTS idx_maint_status ON public.maintenance_tasks(status);
CREATE INDEX IF NOT EXISTS idx_maint_deleted ON public.maintenance_tasks(deleted_at) WHERE deleted_at IS NULL;

-- Enable Row Level Security (RLS)
ALTER TABLE public.maintenance_tasks ENABLE ROW LEVEL SECURITY;

-- RLS Policies
DROP POLICY IF EXISTS "Admins full access to maintenance_tasks" ON public.maintenance_tasks;
CREATE POLICY "Admins full access to maintenance_tasks" ON public.maintenance_tasks FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Tenants view own maintenance_tasks" ON public.maintenance_tasks;
CREATE POLICY "Tenants view own maintenance_tasks" ON public.maintenance_tasks FOR SELECT TO authenticated USING (
  (
    reported_by = auth.uid()
    OR renter_id IN (
      SELECT id FROM public.renters 
      WHERE (
        user_id = auth.uid() 
        OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
        OR (
          LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
          AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
        )
      )
      AND deleted_at IS NULL
    )
  )
  AND deleted_at IS NULL
);

DROP POLICY IF EXISTS "Tenants submit maintenance_tasks" ON public.maintenance_tasks;
CREATE POLICY "Tenants submit maintenance_tasks" ON public.maintenance_tasks FOR INSERT TO authenticated WITH CHECK (
  reported_by = auth.uid() OR
  renter_id IN (
    SELECT id FROM public.renters 
    WHERE (
      user_id = auth.uid() 
      OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
      OR (
        LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
        AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
      )
    )
    AND deleted_at IS NULL
  )
);
