-- ============================================================================
-- 🏢 RENTBILL PRO — ROBUST PRODUCTION DATABASE UPDATE & MIGRATION (100% AUDITED)
-- Safe to run on ANY existing or new Supabase PostgreSQL instance.
-- Preserves all existing properties, units, tenants, invoices, and payments.
-- ============================================================================

-- 1. Ensure required extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. Maintenance Tasks & Repair Work Orders Table
CREATE TABLE IF NOT EXISTS public.maintenance_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    title TEXT NOT NULL,
    description TEXT,
    category TEXT NOT NULL DEFAULT 'PLUMBING' CHECK (category IN ('PLUMBING', 'ELECTRICAL', 'APPLIANCE', 'CLEANING', 'PAINTING', 'CARPENTRY', 'GENERAL', 'OTHER')),
    priority TEXT NOT NULL DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    property_id BIGINT REFERENCES public.properties(id) ON DELETE SET NULL,
    unit_id BIGINT REFERENCES public.units(id) ON DELETE SET NULL,
    renter_id BIGINT REFERENCES public.renters(id) ON DELETE SET NULL,
    reported_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    assigned_to TEXT,
    estimated_cost BIGINT DEFAULT 0,
    actual_cost BIGINT DEFAULT 0,
    scheduled_date DATE,
    completed_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_maint_property ON public.maintenance_tasks(property_id);
CREATE INDEX IF NOT EXISTS idx_maint_unit ON public.maintenance_tasks(unit_id);
CREATE INDEX IF NOT EXISTS idx_maint_renter ON public.maintenance_tasks(renter_id);
CREATE INDEX IF NOT EXISTS idx_maint_status ON public.maintenance_tasks(status);

-- 3. Dynamic Foreign Key Constraint Upgrade (Fix User Deletion Constraint Errors)
DO $$
BEGIN
  ALTER TABLE public.bills DROP CONSTRAINT IF EXISTS bills_voided_by_fkey;
  ALTER TABLE public.bills ADD CONSTRAINT bills_voided_by_fkey FOREIGN KEY (voided_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_verified_by_fkey;
  ALTER TABLE public.payments ADD CONSTRAINT payments_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id) ON DELETE SET NULL;
  
  ALTER TABLE public.payments DROP CONSTRAINT IF EXISTS payments_reversed_by_fkey;
  ALTER TABLE public.payments ADD CONSTRAINT payments_reversed_by_fkey FOREIGN KEY (reversed_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.expenses DROP CONSTRAINT IF EXISTS expenses_created_by_fkey;
  ALTER TABLE public.expenses ADD CONSTRAINT expenses_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.owner_withdrawals DROP CONSTRAINT IF EXISTS owner_withdrawals_created_by_fkey;
  ALTER TABLE public.owner_withdrawals ADD CONSTRAINT owner_withdrawals_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;

  ALTER TABLE public.documents DROP CONSTRAINT IF EXISTS documents_created_by_fkey;
  ALTER TABLE public.documents ADD CONSTRAINT documents_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id) ON DELETE SET NULL;
EXCEPTION WHEN OTHERS THEN
  NULL;
END $$;

-- 4. Pure Admin Security Guard Function
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
DECLARE
  v_role TEXT;
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN FALSE;
  END IF;
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  RETURN COALESCE(v_role = 'ADMIN', FALSE);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 5. Updated Row Level Security (RLS) Policies
ALTER TABLE public.properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.units ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.renters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.owner_withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_tasks ENABLE ROW LEVEL SECURITY;

-- Tenants View Own Lease
DROP POLICY IF EXISTS "Tenants view own lease" ON public.renters;
CREATE POLICY "Tenants view own lease" ON public.renters FOR SELECT TO authenticated USING (
  (
    user_id = auth.uid() 
    OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
    OR (
      LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
      AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
    )
  )
  AND deleted_at IS NULL
);

-- Tenants View Own Bills
DROP POLICY IF EXISTS "Tenants view own bills" ON public.bills;
CREATE POLICY "Tenants view own bills" ON public.bills FOR SELECT TO authenticated USING (
  renter_id IN (
    SELECT id FROM public.renters 
    WHERE (
      user_id = auth.uid() 
      OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
      OR (
        LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
        AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
      )
    )
    AND deleted_at IS NULL
  )
  AND deleted_at IS NULL
);

-- Tenants View Own Payments
DROP POLICY IF EXISTS "Tenants view own payments" ON public.payments;
CREATE POLICY "Tenants view own payments" ON public.payments FOR SELECT TO authenticated USING (
  renter_id IN (
    SELECT id FROM public.renters 
    WHERE (
      user_id = auth.uid() 
      OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
      OR (
        LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
        AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
      )
    )
    AND deleted_at IS NULL
  )
  AND deleted_at IS NULL
);

-- Maintenance Tasks Policies
DROP POLICY IF EXISTS "Admins full access to maintenance_tasks" ON public.maintenance_tasks;
CREATE POLICY "Admins full access to maintenance_tasks" ON public.maintenance_tasks FOR ALL TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Tenants view own maintenance_tasks" ON public.maintenance_tasks;
CREATE POLICY "Tenants view own maintenance_tasks" ON public.maintenance_tasks FOR SELECT TO authenticated USING (
  (
    reported_by = auth.uid()
    OR renter_id IN (
      SELECT id FROM public.renters 
      WHERE (
        user_id = auth.uid() 
        OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
        OR (
          LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
          AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
        )
      )
      AND deleted_at IS NULL
    )
  )
  AND deleted_at IS NULL
);

DROP POLICY IF EXISTS "Tenants submit maintenance_tasks" ON public.maintenance_tasks;
CREATE POLICY "Tenants submit maintenance_tasks" ON public.maintenance_tasks FOR INSERT TO authenticated WITH CHECK (
  reported_by = auth.uid() OR
  renter_id IN (
    SELECT id FROM public.renters 
    WHERE (
      user_id = auth.uid() 
      OR (email IS NOT NULL AND LOWER(TRIM(email)) = LOWER(TRIM(auth.email())))
      OR (
        LENGTH(REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g')) >= 7
        AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || REGEXP_REPLACE(COALESCE(auth.email(), ''), '[^0-9]', '', 'g') || '%'
      )
    )
    AND deleted_at IS NULL
  )
);

-- 6. Authentication RPC Functions (Universal Login & Tenant Management)

-- Resolve Login Email (Universal login wrapper)
DROP FUNCTION IF EXISTS public.get_login_email_for_identifier(TEXT);
DROP FUNCTION IF EXISTS public.resolve_login_email(TEXT);

CREATE OR REPLACE FUNCTION public.get_login_email_for_identifier(p_identifier TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_clean TEXT := TRIM(COALESCE(p_identifier, ''));
  v_email TEXT;
  v_digits TEXT;
BEGIN
  IF v_clean = '' THEN
    RETURN NULL;
  END IF;

  -- 1. Direct match in auth.users or renters by email
  IF v_clean LIKE '%@%' THEN
    SELECT email INTO v_email FROM auth.users WHERE LOWER(email) = LOWER(v_clean) LIMIT 1;
    IF v_email IS NOT NULL THEN RETURN LOWER(v_email); END IF;

    SELECT email INTO v_email FROM public.renters 
    WHERE LOWER(email) = LOWER(v_clean) AND deleted_at IS NULL
    ORDER BY is_active DESC LIMIT 1;
    IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN RETURN LOWER(v_email); END IF;

    -- Check if inverted: mobile_number column holds the email
    SELECT mobile_number INTO v_email FROM public.renters 
    WHERE LOWER(mobile_number) = LOWER(v_clean) AND deleted_at IS NULL
    ORDER BY is_active DESC LIMIT 1;
    IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN RETURN LOWER(v_email); END IF;
  END IF;

  -- 2. Digits match for mobile number
  v_digits := REGEXP_REPLACE(v_clean, '[^0-9]', '', 'g');
  IF LENGTH(v_digits) >= 7 THEN
    -- Match in auth.users by email containing digits or mobile metadata
    SELECT email INTO v_email FROM auth.users 
    WHERE (REGEXP_REPLACE(email, '[^0-9]', '', 'g') LIKE '%' || v_digits || '%' OR raw_user_meta_data->>'mobile' LIKE '%' || v_digits || '%')
    LIMIT 1;
    IF v_email IS NOT NULL THEN RETURN LOWER(v_email); END IF;

    -- Match in renters table by mobile_number or email digits
    SELECT 
      CASE 
        WHEN email LIKE '%@%' THEN email 
        WHEN mobile_number LIKE '%@%' THEN mobile_number 
        ELSE NULL 
      END INTO v_email
    FROM public.renters 
    WHERE (REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || v_digits || '%' OR REGEXP_REPLACE(email, '[^0-9]', '', 'g') LIKE '%' || v_digits || '%')
      AND deleted_at IS NULL
    ORDER BY is_active DESC LIMIT 1;
    
    IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN RETURN LOWER(v_email); END IF;

    -- Fallback check for generated local email
    SELECT email INTO v_email FROM auth.users 
    WHERE LOWER(email) = LOWER('tenant_' || v_digits || '@rentbill.local') LIMIT 1;
    IF v_email IS NOT NULL THEN RETURN LOWER(v_email); END IF;
  END IF;

  -- 3. Match in profiles by username or renters by name
  SELECT u.email INTO v_email FROM auth.users u
  JOIN public.profiles p ON u.id = p.id
  WHERE LOWER(p.username) = LOWER(v_clean) LIMIT 1;
  IF v_email IS NOT NULL THEN RETURN LOWER(v_email); END IF;

  SELECT 
    CASE 
      WHEN email LIKE '%@%' THEN email 
      WHEN mobile_number LIKE '%@%' THEN mobile_number 
      ELSE NULL 
    END INTO v_email
  FROM public.renters 
  WHERE LOWER(name) = LOWER(v_clean) AND deleted_at IS NULL
  ORDER BY is_active DESC LIMIT 1;
  
  IF v_email IS NOT NULL AND v_email LIKE '%@%' THEN RETURN LOWER(v_email); END IF;

  RETURN CASE WHEN v_clean LIKE '%@%' THEN LOWER(v_clean) ELSE NULL END;
END;
$$;

CREATE OR REPLACE FUNCTION public.resolve_login_email(p_identifier TEXT)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  RETURN public.get_login_email_for_identifier(p_identifier);
END;
$$;

-- Admin List Tenants with Auth (Auto-swaps inverted email/phone)
DROP FUNCTION IF EXISTS public.admin_list_tenants_with_auth();
CREATE OR REPLACE FUNCTION public.admin_list_tenants_with_auth()
RETURNS TABLE (
  renter_id BIGINT,
  renter_name TEXT,
  mobile_number TEXT,
  email TEXT,
  unit_name TEXT,
  property_name TEXT,
  user_id UUID,
  has_auth_account BOOLEAN,
  last_sign_in_at TIMESTAMPTZ,
  is_active BOOLEAN,
  is_disabled BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can view tenant credentials.';
  END IF;

  RETURN QUERY
  SELECT 
    r.id AS renter_id,
    r.name AS renter_name,
    CASE 
      WHEN r.mobile_number LIKE '%@%' AND (r.email IS NULL OR r.email NOT LIKE '%@%') THEN r.email
      ELSE r.mobile_number 
    END AS mobile_number,
    CASE 
      WHEN r.mobile_number LIKE '%@%' AND (r.email IS NULL OR r.email NOT LIKE '%@%') THEN r.mobile_number
      ELSE r.email 
    END AS email,
    u.unit_name,
    p.name AS property_name,
    r.user_id,
    (u_auth.id IS NOT NULL) AS has_auth_account,
    u_auth.last_sign_in_at,
    r.is_active,
    COALESCE(prof.is_disabled, u_auth.banned_until > NOW(), FALSE) AS is_disabled
  FROM public.renters r
  LEFT JOIN public.units u ON r.unit_id = u.id
  LEFT JOIN public.properties p ON u.property_id = p.id
  LEFT JOIN auth.users u_auth ON (r.user_id = u_auth.id OR (r.email IS NOT NULL AND LOWER(r.email) = LOWER(u_auth.email)))
  LEFT JOIN public.profiles prof ON u_auth.id = prof.id
  WHERE r.deleted_at IS NULL
  ORDER BY r.is_active DESC, r.name ASC;
END;
$$;

-- Admin Delete Tenant Login (Robust Foreign Key Nullification)
DROP FUNCTION IF EXISTS public.admin_delete_tenant_login(BIGINT, UUID);
CREATE OR REPLACE FUNCTION public.admin_delete_tenant_login(
  p_renter_id BIGINT,
  p_user_id UUID DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_uid UUID := p_user_id;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Access denied. Only administrators can delete tenant login accounts.';
  END IF;

  IF v_uid IS NULL AND p_renter_id IS NOT NULL THEN
    SELECT user_id INTO v_uid FROM public.renters WHERE id = p_renter_id;
  END IF;

  IF p_renter_id IS NOT NULL THEN
    UPDATE public.renters SET user_id = NULL, updated_at = NOW() WHERE id = p_renter_id;
  END IF;

  IF v_uid IS NOT NULL THEN
    UPDATE public.renters SET user_id = NULL WHERE user_id = v_uid;
    UPDATE public.bills SET voided_by = NULL WHERE voided_by = v_uid;
    UPDATE public.payments SET verified_by = NULL WHERE verified_by = v_uid;
    UPDATE public.payments SET reversed_by = NULL WHERE reversed_by = v_uid;
    UPDATE public.expenses SET created_by = NULL WHERE created_by = v_uid;
    UPDATE public.owner_withdrawals SET created_by = NULL WHERE created_by = v_uid;
    UPDATE public.documents SET created_by = NULL WHERE created_by = v_uid;
    UPDATE public.maintenance_tasks SET reported_by = NULL WHERE reported_by = v_uid;

    BEGIN
      DELETE FROM auth.mfa_amr_claims WHERE session_id IN (SELECT id FROM auth.sessions WHERE user_id = v_uid);
      DELETE FROM auth.mfa_factors WHERE user_id = v_uid;
      DELETE FROM auth.sessions WHERE user_id = v_uid;
      DELETE FROM auth.refresh_tokens WHERE session_id IN (SELECT id FROM auth.sessions WHERE user_id = v_uid);
      DELETE FROM auth.identities WHERE user_id = v_uid;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;

    DELETE FROM public.profiles WHERE id = v_uid;

    BEGIN
      DELETE FROM auth.users WHERE id = v_uid;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END IF;

  RETURN jsonb_build_object('success', true, 'message', 'Tenant login account deleted successfully');
END;
$$;

-- Auto-link tenant own lease upon login
DROP FUNCTION IF EXISTS public.tenant_link_own_lease();
CREATE OR REPLACE FUNCTION public.tenant_link_own_lease()
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_email TEXT := auth.email();
  v_digits TEXT;
  v_prof_email TEXT;
  v_meta_renter_id BIGINT;
BEGIN
  IF v_uid IS NULL THEN
    RETURN jsonb_build_object('success', false, 'message', 'Unauthenticated');
  END IF;

  SELECT email INTO v_prof_email FROM public.profiles WHERE id = v_uid;
  BEGIN
    SELECT (raw_user_meta_data->>'renter_id')::BIGINT INTO v_meta_renter_id FROM auth.users WHERE id = v_uid;
  EXCEPTION WHEN OTHERS THEN
    v_meta_renter_id := NULL;
  END;

  v_digits := REGEXP_REPLACE(COALESCE(v_email, ''), '[^0-9]', '', 'g');

  UPDATE public.renters
  SET user_id = v_uid, updated_at = NOW()
  WHERE deleted_at IS NULL
    AND (
      user_id = v_uid
      OR (v_meta_renter_id IS NOT NULL AND id = v_meta_renter_id)
      OR (v_email IS NOT NULL AND v_email != '' AND LOWER(TRIM(email)) = LOWER(TRIM(v_email)))
      OR (v_prof_email IS NOT NULL AND v_prof_email != '' AND LOWER(TRIM(email)) = LOWER(TRIM(v_prof_email)))
      OR (v_email IS NOT NULL AND v_email != '' AND LOWER(TRIM(mobile_number)) = LOWER(TRIM(v_email)))
      OR (LENGTH(v_digits) >= 7 AND REGEXP_REPLACE(mobile_number, '[^0-9]', '', 'g') LIKE '%' || v_digits || '%')
    );

  RETURN jsonb_build_object('success', true);
END;
$$;

-- 7. Grant execution permissions
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.get_login_email_for_identifier(TEXT) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.resolve_login_email(TEXT) TO authenticated, anon;
GRANT EXECUTE ON FUNCTION public.admin_list_tenants_with_auth() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_create_tenant_user(TEXT, TEXT, TEXT, BIGINT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_reset_tenant_password(UUID, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_delete_tenant_login(BIGINT, UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.tenant_link_own_lease() TO authenticated;
